# coding: utf-8

from __future__ import annotations
from datetime import date, datetime  # noqa: F401

import re  # noqa: F401
from typing import Any, Dict, List, Optional  # noqa: F401

from pydantic import AnyUrl, BaseModel, EmailStr, Field, validator  # noqa: F401


class ACCLDisallowedAttributes(BaseModel):
    """NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).

    Do not edit the class manually.

    ACCLDisallowedAttributes - a model defined in OpenAPI

        managed_entity_identifier: The managed_entity_identifier of this ACCLDisallowedAttributes [Optional].
        attribute_name_list: The attribute_name_list of this ACCLDisallowedAttributes [Optional].
    """

    managed_entity_identifier: Optional[str] = Field(alias="managedEntityIdentifier", default=None)
    attribute_name_list: Optional[List[str]] = Field(alias="attributeNameList", default=None)

ACCLDisallowedAttributes.update_forward_refs()
