# coding: utf-8

from __future__ import annotations
from datetime import date, datetime  # noqa: F401

import re  # noqa: F401
from typing import Any, Dict, List, Optional  # noqa: F401

from pydantic import AnyUrl, BaseModel, EmailStr, Field, validator  # noqa: F401
from openapi_server.models.amf_identifier import AmfIdentifier
from openapi_server.models.comm_model import CommModel
from openapi_server.models.guam_info import GUAMInfo
from openapi_server.models.managed_nf_profile import ManagedNFProfile
from openapi_server.models.plmn_info import PlmnInfo
from openapi_server.models.tai import Tai
from openapi_server.models.tai_range import TaiRange


class AmfFunctionSingleAllOfAttributesAllOf(BaseModel):
    """NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).

    Do not edit the class manually.

    AmfFunctionSingleAllOfAttributesAllOf - a model defined in OpenAPI

        p_lmn_info_list: The p_lmn_info_list of this AmfFunctionSingleAllOfAttributesAllOf [Optional].
        amf_identifier: The amf_identifier of this AmfFunctionSingleAllOfAttributesAllOf [Optional].
        s_bi_fqdn: The s_bi_fqdn of this AmfFunctionSingleAllOfAttributesAllOf [Optional].
        inter_plmn_fqdn: The inter_plmn_fqdn of this AmfFunctionSingleAllOfAttributesAllOf [Optional].
        tai_list: The tai_list of this AmfFunctionSingleAllOfAttributesAllOf [Optional].
        tai_range_list: The tai_range_list of this AmfFunctionSingleAllOfAttributesAllOf [Optional].
        weight_factor: The weight_factor of this AmfFunctionSingleAllOfAttributesAllOf [Optional].
        c_nsiid_list: The c_nsiid_list of this AmfFunctionSingleAllOfAttributesAllOf [Optional].
        g_uamid_list: The g_uamid_list of this AmfFunctionSingleAllOfAttributesAllOf [Optional].
        backup_info_amf_failure: The backup_info_amf_failure of this AmfFunctionSingleAllOfAttributesAllOf [Optional].
        backup_info_amf_removal: The backup_info_amf_removal of this AmfFunctionSingleAllOfAttributesAllOf [Optional].
        amf_set_ref: The amf_set_ref of this AmfFunctionSingleAllOfAttributesAllOf [Optional].
        managed_nf_profile: The managed_nf_profile of this AmfFunctionSingleAllOfAttributesAllOf [Optional].
        comm_model_list: The comm_model_list of this AmfFunctionSingleAllOfAttributesAllOf [Optional].
    """

    p_lmn_info_list: Optional[List[PlmnInfo]] = Field(alias="pLMNInfoList", default=None)
    amf_identifier: Optional[AmfIdentifier] = Field(alias="amfIdentifier", default=None)
    s_bi_fqdn: Optional[str] = Field(alias="sBIFqdn", default=None)
    inter_plmn_fqdn: Optional[str] = Field(alias="interPlmnFQDN", default=None)
    tai_list: Optional[List[Tai]] = Field(alias="taiList", default=None)
    tai_range_list: Optional[List[TaiRange]] = Field(alias="taiRangeList", default=None)
    weight_factor: Optional[int] = Field(alias="weightFactor", default=None)
    c_nsiid_list: Optional[List[str]] = Field(alias="cNSIIdList", default=None)
    g_uamid_list: Optional[List[GUAMInfo]] = Field(alias="gUAMIdList", default=None)
    backup_info_amf_failure: Optional[List[GUAMInfo]] = Field(alias="backupInfoAmfFailure", default=None)
    backup_info_amf_removal: Optional[List[GUAMInfo]] = Field(alias="backupInfoAmfRemoval", default=None)
    amf_set_ref: Optional[str] = Field(alias="amfSetRef", default=None)
    managed_nf_profile: Optional[ManagedNFProfile] = Field(alias="managedNFProfile", default=None)
    comm_model_list: Optional[List[CommModel]] = Field(alias="commModelList", default=None)

AmfFunctionSingleAllOfAttributesAllOf.update_forward_refs()
