# coding: utf-8

from __future__ import annotations
from datetime import date, datetime  # noqa: F401

import re  # noqa: F401
from typing import Any, Dict, List, Optional  # noqa: F401

from pydantic import AnyUrl, BaseModel, EmailStr, Field, validator  # noqa: F401
from openapi_server.models.amf_identifier import AmfIdentifier
from openapi_server.models.comm_model import CommModel
from openapi_server.models.guam_info import GUAMInfo
from openapi_server.models.managed_nf_profile import ManagedNFProfile
from openapi_server.models.pee_parameter import PeeParameter
from openapi_server.models.plmn_info import PlmnInfo
from openapi_server.models.supported_perf_metric_group import SupportedPerfMetricGroup
from openapi_server.models.tai import Tai
from openapi_server.models.tai_range import TaiRange
from openapi_server.models.vnf_parameter import VnfParameter


class AmfFunctionSingleAllOfAttributes(BaseModel):
    """NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).

    Do not edit the class manually.

    AmfFunctionSingleAllOfAttributes - a model defined in OpenAPI

        user_label: The user_label of this AmfFunctionSingleAllOfAttributes [Optional].
        vnf_parameters_list: The vnf_parameters_list of this AmfFunctionSingleAllOfAttributes [Optional].
        pee_parameters_list: The pee_parameters_list of this AmfFunctionSingleAllOfAttributes [Optional].
        priority_label: The priority_label of this AmfFunctionSingleAllOfAttributes [Optional].
        supported_perf_metric_groups: The supported_perf_metric_groups of this AmfFunctionSingleAllOfAttributes [Optional].
        supported_trace_metrics: The supported_trace_metrics of this AmfFunctionSingleAllOfAttributes [Optional].
        p_lmn_info_list: The p_lmn_info_list of this AmfFunctionSingleAllOfAttributes [Optional].
        amf_identifier: The amf_identifier of this AmfFunctionSingleAllOfAttributes [Optional].
        s_bi_fqdn: The s_bi_fqdn of this AmfFunctionSingleAllOfAttributes [Optional].
        inter_plmn_fqdn: The inter_plmn_fqdn of this AmfFunctionSingleAllOfAttributes [Optional].
        tai_list: The tai_list of this AmfFunctionSingleAllOfAttributes [Optional].
        tai_range_list: The tai_range_list of this AmfFunctionSingleAllOfAttributes [Optional].
        weight_factor: The weight_factor of this AmfFunctionSingleAllOfAttributes [Optional].
        c_nsiid_list: The c_nsiid_list of this AmfFunctionSingleAllOfAttributes [Optional].
        g_uamid_list: The g_uamid_list of this AmfFunctionSingleAllOfAttributes [Optional].
        backup_info_amf_failure: The backup_info_amf_failure of this AmfFunctionSingleAllOfAttributes [Optional].
        backup_info_amf_removal: The backup_info_amf_removal of this AmfFunctionSingleAllOfAttributes [Optional].
        amf_set_ref: The amf_set_ref of this AmfFunctionSingleAllOfAttributes [Optional].
        managed_nf_profile: The managed_nf_profile of this AmfFunctionSingleAllOfAttributes [Optional].
        comm_model_list: The comm_model_list of this AmfFunctionSingleAllOfAttributes [Optional].
    """

    user_label: Optional[str] = Field(alias="userLabel", default=None)
    vnf_parameters_list: Optional[List[VnfParameter]] = Field(alias="vnfParametersList", default=None)
    pee_parameters_list: Optional[List[PeeParameter]] = Field(alias="peeParametersList", default=None)
    priority_label: Optional[int] = Field(alias="priorityLabel", default=None)
    supported_perf_metric_groups: Optional[List[SupportedPerfMetricGroup]] = Field(alias="supportedPerfMetricGroups", default=None)
    supported_trace_metrics: Optional[List[str]] = Field(alias="supportedTraceMetrics", default=None)
    p_lmn_info_list: Optional[List[PlmnInfo]] = Field(alias="pLMNInfoList", default=None)
    amf_identifier: Optional[AmfIdentifier] = Field(alias="amfIdentifier", default=None)
    s_bi_fqdn: Optional[str] = Field(alias="sBIFqdn", default=None)
    inter_plmn_fqdn: Optional[str] = Field(alias="interPlmnFQDN", default=None)
    tai_list: Optional[List[Tai]] = Field(alias="taiList", default=None)
    tai_range_list: Optional[List[TaiRange]] = Field(alias="taiRangeList", default=None)
    weight_factor: Optional[int] = Field(alias="weightFactor", default=None)
    c_nsiid_list: Optional[List[str]] = Field(alias="cNSIIdList", default=None)
    g_uamid_list: Optional[List[GUAMInfo]] = Field(alias="gUAMIdList", default=None)
    backup_info_amf_failure: Optional[List[GUAMInfo]] = Field(alias="backupInfoAmfFailure", default=None)
    backup_info_amf_removal: Optional[List[GUAMInfo]] = Field(alias="backupInfoAmfRemoval", default=None)
    amf_set_ref: Optional[str] = Field(alias="amfSetRef", default=None)
    managed_nf_profile: Optional[ManagedNFProfile] = Field(alias="managedNFProfile", default=None)
    comm_model_list: Optional[List[CommModel]] = Field(alias="commModelList", default=None)

AmfFunctionSingleAllOfAttributes.update_forward_refs()
