# coding: utf-8

from __future__ import annotations
from datetime import date, datetime  # noqa: F401

import re  # noqa: F401
from typing import Any, Dict, List, Optional  # noqa: F401

from pydantic import AnyUrl, BaseModel, EmailStr, Field, validator  # noqa: F401
from openapi_server.models.delay_tolerance import DelayTolerance
from openapi_server.models.deterministic_comm import DeterministicComm
from openapi_server.models.n6_protection import N6Protection
from openapi_server.models.nssaa_support import NSSAASupport
from openapi_server.models.sharing_level import SharingLevel
from openapi_server.models.slice_simultaneous_use import SliceSimultaneousUse
from openapi_server.models.synchronicity_ran_subnet import SynchronicityRANSubnet
from openapi_server.models.xl_thpt import XLThpt


class CNSliceSubnetProfile(BaseModel):
    """NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).

    Do not edit the class manually.

    CNSliceSubnetProfile - a model defined in OpenAPI

        max_numberof_ues: The max_numberof_ues of this CNSliceSubnetProfile [Optional].
        d_l_latency: The d_l_latency of this CNSliceSubnetProfile [Optional].
        u_l_latency: The u_l_latency of this CNSliceSubnetProfile [Optional].
        d_l_thpt_per_slice_subnet: The d_l_thpt_per_slice_subnet of this CNSliceSubnetProfile [Optional].
        d_l_thpt_per_ue: The d_l_thpt_per_ue of this CNSliceSubnetProfile [Optional].
        u_l_thpt_per_slice_subnet: The u_l_thpt_per_slice_subnet of this CNSliceSubnetProfile [Optional].
        u_l_thpt_per_ue: The u_l_thpt_per_ue of this CNSliceSubnetProfile [Optional].
        max_number_of_pdu_sessions: The max_number_of_pdu_sessions of this CNSliceSubnetProfile [Optional].
        coverage_area_ta_list: The coverage_area_ta_list of this CNSliceSubnetProfile [Optional].
        resource_sharing_level: The resource_sharing_level of this CNSliceSubnetProfile [Optional].
        d_l_max_pkt_size: The d_l_max_pkt_size of this CNSliceSubnetProfile [Optional].
        u_l_max_pkt_size: The u_l_max_pkt_size of this CNSliceSubnetProfile [Optional].
        delay_tolerance: The delay_tolerance of this CNSliceSubnetProfile [Optional].
        synchronicity: The synchronicity of this CNSliceSubnetProfile [Optional].
        slice_simultaneous_use: The slice_simultaneous_use of this CNSliceSubnetProfile [Optional].
        reliability: The reliability of this CNSliceSubnetProfile [Optional].
        energy_efficiency: The energy_efficiency of this CNSliceSubnetProfile [Optional].
        d_l_deterministic_comm: The d_l_deterministic_comm of this CNSliceSubnetProfile [Optional].
        u_l_deterministic_comm: The u_l_deterministic_comm of this CNSliceSubnetProfile [Optional].
        survival_time: The survival_time of this CNSliceSubnetProfile [Optional].
        nssaa_support: The nssaa_support of this CNSliceSubnetProfile [Optional].
        n6_protection: The n6_protection of this CNSliceSubnetProfile [Optional].
    """

    max_numberof_ues: Optional[int] = Field(alias="maxNumberofUEs", default=None)
    d_l_latency: Optional[float] = Field(alias="dLLatency", default=None)
    u_l_latency: Optional[float] = Field(alias="uLLatency", default=None)
    d_l_thpt_per_slice_subnet: Optional[XLThpt] = Field(alias="dLThptPerSliceSubnet", default=None)
    d_l_thpt_per_ue: Optional[XLThpt] = Field(alias="dLThptPerUE", default=None)
    u_l_thpt_per_slice_subnet: Optional[XLThpt] = Field(alias="uLThptPerSliceSubnet", default=None)
    u_l_thpt_per_ue: Optional[XLThpt] = Field(alias="uLThptPerUE", default=None)
    max_number_of_pdu_sessions: Optional[int] = Field(alias="maxNumberOfPDUSessions", default=None)
    coverage_area_ta_list: Optional[List[int]] = Field(alias="coverageAreaTAList", default=None)
    resource_sharing_level: Optional[SharingLevel] = Field(alias="resourceSharingLevel", default=None)
    d_l_max_pkt_size: Optional[int] = Field(alias="dLMaxPktSize", default=None)
    u_l_max_pkt_size: Optional[int] = Field(alias="uLMaxPktSize", default=None)
    delay_tolerance: Optional[DelayTolerance] = Field(alias="delayTolerance", default=None)
    synchronicity: Optional[SynchronicityRANSubnet] = Field(alias="synchronicity", default=None)
    slice_simultaneous_use: Optional[SliceSimultaneousUse] = Field(alias="sliceSimultaneousUse", default=None)
    reliability: Optional[float] = Field(alias="reliability", default=None)
    energy_efficiency: Optional[float] = Field(alias="energyEfficiency", default=None)
    d_l_deterministic_comm: Optional[DeterministicComm] = Field(alias="dLDeterministicComm", default=None)
    u_l_deterministic_comm: Optional[DeterministicComm] = Field(alias="uLDeterministicComm", default=None)
    survival_time: Optional[float] = Field(alias="survivalTime", default=None)
    nssaa_support: Optional[NSSAASupport] = Field(alias="nssaaSupport", default=None)
    n6_protection: Optional[N6Protection] = Field(alias="n6Protection", default=None)

CNSliceSubnetProfile.update_forward_refs()
