# coding: utf-8

from __future__ import annotations
from datetime import date, datetime  # noqa: F401

import re  # noqa: F401
from typing import Any, Dict, List, Optional  # noqa: F401

from pydantic import AnyUrl, BaseModel, EmailStr, Field, validator  # noqa: F401
from openapi_server.models.beam_single import BeamSingle


class CommonBeamformingFunctionSingleAllOf1(BaseModel):
    """NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).

    Do not edit the class manually.

    CommonBeamformingFunctionSingleAllOf1 - a model defined in OpenAPI

        beam: The beam of this CommonBeamformingFunctionSingleAllOf1 [Optional].
    """

    beam: Optional[List[BeamSingle]] = Field(alias="Beam", default=None)

CommonBeamformingFunctionSingleAllOf1.update_forward_refs()
