# coding: utf-8

from __future__ import annotations
from datetime import date, datetime  # noqa: F401

import re  # noqa: F401
from typing import Any, Dict, List, Optional  # noqa: F401

from pydantic import AnyUrl, BaseModel, EmailStr, Field, validator  # noqa: F401


class CorrelatedNotification(BaseModel):
    """NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).

    Do not edit the class manually.

    CorrelatedNotification - a model defined in OpenAPI

        source: The source of this CorrelatedNotification.
        notification_ids: The notification_ids of this CorrelatedNotification.
    """

    source: str = Field(alias="source")
    notification_ids: List[int] = Field(alias="notificationIds")

CorrelatedNotification.update_forward_refs()
