# coding: utf-8

from __future__ import annotations
from datetime import date, datetime  # noqa: F401

import re  # noqa: F401
from typing import Any, Dict, List, Optional  # noqa: F401

from pydantic import AnyUrl, BaseModel, EmailStr, Field, validator  # noqa: F401
from openapi_server.models.c_son_pci_list import CSonPciList


class CPCIConfigurationFunctionSingleAllOfAttributes(BaseModel):
    """NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).

    Do not edit the class manually.

    CPCIConfigurationFunctionSingleAllOfAttributes - a model defined in OpenAPI

        c_pci_configuration_control: The c_pci_configuration_control of this CPCIConfigurationFunctionSingleAllOfAttributes [Optional].
        c_son_pci_list: The c_son_pci_list of this CPCIConfigurationFunctionSingleAllOfAttributes [Optional].
    """

    c_pci_configuration_control: Optional[bool] = Field(alias="cPciConfigurationControl", default=None)
    c_son_pci_list: Optional[CSonPciList] = Field(alias="cSonPciList", default=None)

CPCIConfigurationFunctionSingleAllOfAttributes.update_forward_refs()
