# coding: utf-8

from __future__ import annotations
from datetime import date, datetime  # noqa: F401

import re  # noqa: F401
from typing import Any, Dict, List, Optional  # noqa: F401

from pydantic import AnyUrl, BaseModel, EmailStr, Field, validator  # noqa: F401
from openapi_server.models.ddnmf_function_single_all_of_attributes import DDNMFFunctionSingleAllOfAttributes
from openapi_server.models.ep_npc4_single import EPNpc4Single
from openapi_server.models.ep_npc6_single import EPNpc6Single
from openapi_server.models.ep_npc7_single import EPNpc7Single
from openapi_server.models.ep_npc8_single import EPNpc8Single
from openapi_server.models.managed_nf_service_single import ManagedNFServiceSingle
from openapi_server.models.perf_metric_job_single import PerfMetricJobSingle
from openapi_server.models.threshold_monitor_single import ThresholdMonitorSingle
from openapi_server.models.trace_job_single import TraceJobSingle
from openapi_server.models.vs_data_container_single import VsDataContainerSingle


class DDNMFFunctionSingle(BaseModel):
    """NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).

    Do not edit the class manually.

    DDNMFFunctionSingle - a model defined in OpenAPI

        id: The id of this DDNMFFunctionSingle.
        object_class: The object_class of this DDNMFFunctionSingle [Optional].
        object_instance: The object_instance of this DDNMFFunctionSingle [Optional].
        vs_data_container: The vs_data_container of this DDNMFFunctionSingle [Optional].
        attributes: The attributes of this DDNMFFunctionSingle [Optional].
        perf_metric_job: The perf_metric_job of this DDNMFFunctionSingle [Optional].
        threshold_monitor: The threshold_monitor of this DDNMFFunctionSingle [Optional].
        managed_nf_service: The managed_nf_service of this DDNMFFunctionSingle [Optional].
        trace_job: The trace_job of this DDNMFFunctionSingle [Optional].
        ep_npc4: The ep_npc4 of this DDNMFFunctionSingle [Optional].
        ep_npc6: The ep_npc6 of this DDNMFFunctionSingle [Optional].
        ep_npc7: The ep_npc7 of this DDNMFFunctionSingle [Optional].
        ep_npc8: The ep_npc8 of this DDNMFFunctionSingle [Optional].
    """

    id: str = Field(alias="id")
    object_class: Optional[str] = Field(alias="objectClass", default=None)
    object_instance: Optional[str] = Field(alias="objectInstance", default=None)
    vs_data_container: Optional[List[VsDataContainerSingle]] = Field(alias="VsDataContainer", default=None)
    attributes: Optional[DDNMFFunctionSingleAllOfAttributes] = Field(alias="attributes", default=None)
    perf_metric_job: Optional[List[PerfMetricJobSingle]] = Field(alias="PerfMetricJob", default=None)
    threshold_monitor: Optional[List[ThresholdMonitorSingle]] = Field(alias="ThresholdMonitor", default=None)
    managed_nf_service: Optional[List[ManagedNFServiceSingle]] = Field(alias="ManagedNFService", default=None)
    trace_job: Optional[List[TraceJobSingle]] = Field(alias="TraceJob", default=None)
    ep_npc4: Optional[List[EPNpc4Single]] = Field(alias="EP_Npc4", default=None)
    ep_npc6: Optional[List[EPNpc6Single]] = Field(alias="EP_Npc6", default=None)
    ep_npc7: Optional[List[EPNpc7Single]] = Field(alias="EP_Npc7", default=None)
    ep_npc8: Optional[List[EPNpc8Single]] = Field(alias="EP_Npc8", default=None)

DDNMFFunctionSingle.update_forward_refs()
