# coding: utf-8

from __future__ import annotations
from datetime import date, datetime  # noqa: F401

import re  # noqa: F401
from typing import Any, Dict, List, Optional  # noqa: F401

from pydantic import AnyUrl, BaseModel, EmailStr, Field, validator  # noqa: F401
from openapi_server.models.five_qi_characteristics_single import FiveQICharacteristicsSingle


class Dynamic5QISetSingleAllOfAttributesAllOf(BaseModel):
    """NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).

    Do not edit the class manually.

    Dynamic5QISetSingleAllOfAttributesAllOf - a model defined in OpenAPI

        dynamic5_qis: The dynamic5_qis of this Dynamic5QISetSingleAllOfAttributesAllOf [Optional].
    """

    dynamic5_qis: Optional[List[FiveQICharacteristicsSingle]] = Field(alias="dynamic5QIs", default=None)

Dynamic5QISetSingleAllOfAttributesAllOf.update_forward_refs()
