# coding: utf-8

from __future__ import annotations
from datetime import date, datetime  # noqa: F401

import re  # noqa: F401
from typing import Any, Dict, List, Optional  # noqa: F401

from pydantic import AnyUrl, BaseModel, EmailStr, Field, validator  # noqa: F401
from openapi_server.models.e_utran_freq_relation_single_all_of_attributes import EUtranFreqRelationSingleAllOfAttributes


class EUtranFreqRelationSingleAllOf(BaseModel):
    """NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).

    Do not edit the class manually.

    EUtranFreqRelationSingleAllOf - a model defined in OpenAPI

        attributes: The attributes of this EUtranFreqRelationSingleAllOf [Optional].
    """

    attributes: Optional[EUtranFreqRelationSingleAllOfAttributes] = Field(alias="attributes", default=None)

EUtranFreqRelationSingleAllOf.update_forward_refs()
