# coding: utf-8

from __future__ import annotations
from datetime import date, datetime  # noqa: F401

import re  # noqa: F401
from typing import Any, Dict, List, Optional  # noqa: F401

from pydantic import AnyUrl, BaseModel, EmailStr, Field, validator  # noqa: F401
from openapi_server.models.managed_nf_profile import ManagedNFProfile
from openapi_server.models.pee_parameter import PeeParameter
from openapi_server.models.plmn_id import PlmnId
from openapi_server.models.supported_perf_metric_group import SupportedPerfMetricGroup
from openapi_server.models.vnf_parameter import VnfParameter


class EASDFFunctionSingleAllOfAttributes(BaseModel):
    """NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).

    Do not edit the class manually.

    EASDFFunctionSingleAllOfAttributes - a model defined in OpenAPI

        user_label: The user_label of this EASDFFunctionSingleAllOfAttributes [Optional].
        vnf_parameters_list: The vnf_parameters_list of this EASDFFunctionSingleAllOfAttributes [Optional].
        pee_parameters_list: The pee_parameters_list of this EASDFFunctionSingleAllOfAttributes [Optional].
        priority_label: The priority_label of this EASDFFunctionSingleAllOfAttributes [Optional].
        supported_perf_metric_groups: The supported_perf_metric_groups of this EASDFFunctionSingleAllOfAttributes [Optional].
        supported_trace_metrics: The supported_trace_metrics of this EASDFFunctionSingleAllOfAttributes [Optional].
        plmn_id: The plmn_id of this EASDFFunctionSingleAllOfAttributes [Optional].
        s_bi_fqdn: The s_bi_fqdn of this EASDFFunctionSingleAllOfAttributes [Optional].
        managed_nf_profile: The managed_nf_profile of this EASDFFunctionSingleAllOfAttributes [Optional].
        server_addr: The server_addr of this EASDFFunctionSingleAllOfAttributes [Optional].
    """

    user_label: Optional[str] = Field(alias="userLabel", default=None)
    vnf_parameters_list: Optional[List[VnfParameter]] = Field(alias="vnfParametersList", default=None)
    pee_parameters_list: Optional[List[PeeParameter]] = Field(alias="peeParametersList", default=None)
    priority_label: Optional[int] = Field(alias="priorityLabel", default=None)
    supported_perf_metric_groups: Optional[List[SupportedPerfMetricGroup]] = Field(alias="supportedPerfMetricGroups", default=None)
    supported_trace_metrics: Optional[List[str]] = Field(alias="supportedTraceMetrics", default=None)
    plmn_id: Optional[PlmnId] = Field(alias="plmnId", default=None)
    s_bi_fqdn: Optional[str] = Field(alias="sBIFqdn", default=None)
    managed_nf_profile: Optional[ManagedNFProfile] = Field(alias="managedNFProfile", default=None)
    server_addr: Optional[str] = Field(alias="serverAddr", default=None)

EASDFFunctionSingleAllOfAttributes.update_forward_refs()
