# coding: utf-8

from __future__ import annotations
from datetime import date, datetime  # noqa: F401

import re  # noqa: F401
from typing import Any, Dict, List, Optional  # noqa: F401

from pydantic import AnyUrl, BaseModel, EmailStr, Field, validator  # noqa: F401
from openapi_server.models.epn88_single import EPN88Single


class EASDFFunctionSingleAllOf1(BaseModel):
    """NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).

    Do not edit the class manually.

    EASDFFunctionSingleAllOf1 - a model defined in OpenAPI

        ep_n88: The ep_n88 of this EASDFFunctionSingleAllOf1 [Optional].
    """

    ep_n88: Optional[List[EPN88Single]] = Field(alias="EP_N88", default=None)

EASDFFunctionSingleAllOf1.update_forward_refs()
