# coding: utf-8

from __future__ import annotations
from datetime import date, datetime  # noqa: F401

import re  # noqa: F401
from typing import Any, Dict, List, Optional  # noqa: F401

from pydantic import AnyUrl, BaseModel, EmailStr, Field, validator  # noqa: F401
from openapi_server.models.ee_perf_req import EEPerfReq
from openapi_server.models.serv_attr_com import ServAttrCom


class EnergyEfficiency(BaseModel):
    """NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).

    Do not edit the class manually.

    EnergyEfficiency - a model defined in OpenAPI

        serv_attr_com: The serv_attr_com of this EnergyEfficiency [Optional].
        performance: The performance of this EnergyEfficiency [Optional].
    """

    serv_attr_com: Optional[ServAttrCom] = Field(alias="servAttrCom", default=None)
    performance: Optional[EEPerfReq] = Field(alias="performance", default=None)

EnergyEfficiency.update_forward_refs()
