# coding: utf-8

from __future__ import annotations
from datetime import date, datetime  # noqa: F401

import re  # noqa: F401
from typing import Any, Dict, List, Optional  # noqa: F401

from pydantic import AnyUrl, BaseModel, EmailStr, Field, validator  # noqa: F401
from openapi_server.models.epf1_u_single_all_of_attributes import EPF1USingleAllOfAttributes


class EPF1USingleAllOf(BaseModel):
    """NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).

    Do not edit the class manually.

    EPF1USingleAllOf - a model defined in OpenAPI

        attributes: The attributes of this EPF1USingleAllOf [Optional].
    """

    attributes: Optional[EPF1USingleAllOfAttributes] = Field(alias="attributes", default=None)

EPF1USingleAllOf.update_forward_refs()
