# coding: utf-8

from __future__ import annotations
from datetime import date, datetime  # noqa: F401

import re  # noqa: F401
from typing import Any, Dict, List, Optional  # noqa: F401

from pydantic import AnyUrl, BaseModel, EmailStr, Field, validator  # noqa: F401


class EsNotAllowedTimePeriod(BaseModel):
    """NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).

    Do not edit the class manually.

    EsNotAllowedTimePeriod - a model defined in OpenAPI

        start_timeandend_time: The start_timeandend_time of this EsNotAllowedTimePeriod [Optional].
        period_of_day: The period_of_day of this EsNotAllowedTimePeriod [Optional].
        days_of_week_list: The days_of_week_list of this EsNotAllowedTimePeriod [Optional].
        listoftimeperiods: The listoftimeperiods of this EsNotAllowedTimePeriod [Optional].
    """

    start_timeandend_time: Optional[str] = Field(alias="startTimeandendTime", default=None)
    period_of_day: Optional[str] = Field(alias="periodOfDay", default=None)
    days_of_week_list: Optional[str] = Field(alias="daysOfWeekList", default=None)
    listoftimeperiods: Optional[str] = Field(alias="listoftimeperiods", default=None)

EsNotAllowedTimePeriod.update_forward_refs()
