# coding: utf-8

from __future__ import annotations
from datetime import date, datetime  # noqa: F401

import re  # noqa: F401
from typing import Any, Dict, List, Optional  # noqa: F401

from pydantic import AnyUrl, BaseModel, EmailStr, Field, validator  # noqa: F401
from openapi_server.models.epe1_single import EPE1Single
from openapi_server.models.epf1_c_single import EPF1CSingle
from openapi_server.models.epxn_c_single import EPXnCSingle
from openapi_server.models.external_gnb_cu_cp_function_single_all_of_attributes import ExternalGnbCuCpFunctionSingleAllOfAttributes
from openapi_server.models.external_nr_cell_cu_single import ExternalNrCellCuSingle
from openapi_server.models.managed_nf_service_single import ManagedNFServiceSingle
from openapi_server.models.perf_metric_job_single import PerfMetricJobSingle
from openapi_server.models.threshold_monitor_single import ThresholdMonitorSingle
from openapi_server.models.trace_job_single import TraceJobSingle
from openapi_server.models.vs_data_container_single import VsDataContainerSingle


class ExternalGnbCuCpFunctionSingle(BaseModel):
    """NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).

    Do not edit the class manually.

    ExternalGnbCuCpFunctionSingle - a model defined in OpenAPI

        id: The id of this ExternalGnbCuCpFunctionSingle.
        object_class: The object_class of this ExternalGnbCuCpFunctionSingle [Optional].
        object_instance: The object_instance of this ExternalGnbCuCpFunctionSingle [Optional].
        vs_data_container: The vs_data_container of this ExternalGnbCuCpFunctionSingle [Optional].
        attributes: The attributes of this ExternalGnbCuCpFunctionSingle [Optional].
        perf_metric_job: The perf_metric_job of this ExternalGnbCuCpFunctionSingle [Optional].
        threshold_monitor: The threshold_monitor of this ExternalGnbCuCpFunctionSingle [Optional].
        managed_nf_service: The managed_nf_service of this ExternalGnbCuCpFunctionSingle [Optional].
        trace_job: The trace_job of this ExternalGnbCuCpFunctionSingle [Optional].
        external_nr_cell_cu: The external_nr_cell_cu of this ExternalGnbCuCpFunctionSingle [Optional].
        ep_xn_c: The ep_xn_c of this ExternalGnbCuCpFunctionSingle [Optional].
        ep_e1: The ep_e1 of this ExternalGnbCuCpFunctionSingle [Optional].
        ep_f1_c: The ep_f1_c of this ExternalGnbCuCpFunctionSingle [Optional].
    """

    id: str = Field(alias="id")
    object_class: Optional[str] = Field(alias="objectClass", default=None)
    object_instance: Optional[str] = Field(alias="objectInstance", default=None)
    vs_data_container: Optional[List[VsDataContainerSingle]] = Field(alias="VsDataContainer", default=None)
    attributes: Optional[ExternalGnbCuCpFunctionSingleAllOfAttributes] = Field(alias="attributes", default=None)
    perf_metric_job: Optional[List[PerfMetricJobSingle]] = Field(alias="PerfMetricJob", default=None)
    threshold_monitor: Optional[List[ThresholdMonitorSingle]] = Field(alias="ThresholdMonitor", default=None)
    managed_nf_service: Optional[List[ManagedNFServiceSingle]] = Field(alias="ManagedNFService", default=None)
    trace_job: Optional[List[TraceJobSingle]] = Field(alias="TraceJob", default=None)
    external_nr_cell_cu: Optional[List[ExternalNrCellCuSingle]] = Field(alias="ExternalNrCellCu", default=None)
    ep_xn_c: Optional[List[EPXnCSingle]] = Field(alias="EP_XnC", default=None)
    ep_e1: Optional[List[EPE1Single]] = Field(alias="EP_E1", default=None)
    ep_f1_c: Optional[List[EPF1CSingle]] = Field(alias="EP_F1C", default=None)

ExternalGnbCuCpFunctionSingle.update_forward_refs()
