# coding: utf-8

from __future__ import annotations
from datetime import date, datetime  # noqa: F401

import re  # noqa: F401
from typing import Any, Dict, List, Optional  # noqa: F401

from pydantic import AnyUrl, BaseModel, EmailStr, Field, validator  # noqa: F401


class ExternalENBFunctionSingleAllOfAttributesAllOf(BaseModel):
    """NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).

    Do not edit the class manually.

    ExternalENBFunctionSingleAllOfAttributesAllOf - a model defined in OpenAPI

        e_nbid: The e_nbid of this ExternalENBFunctionSingleAllOfAttributesAllOf [Optional].
    """

    e_nbid: Optional[int] = Field(alias="eNBId", default=None)

ExternalENBFunctionSingleAllOfAttributesAllOf.update_forward_refs()
