# coding: utf-8

from __future__ import annotations
from datetime import date, datetime  # noqa: F401

import re  # noqa: F401
from typing import Any, Dict, List, Optional  # noqa: F401

from pydantic import AnyUrl, BaseModel, EmailStr, Field, validator  # noqa: F401
from openapi_server.models.file_single import FileSingle


class FilesSingleAllOfAttributes(BaseModel):
    """NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).

    Do not edit the class manually.

    FilesSingleAllOfAttributes - a model defined in OpenAPI

        number_of_files: The number_of_files of this FilesSingleAllOfAttributes [Optional].
        job_ref: The job_ref of this FilesSingleAllOfAttributes [Optional].
        job_id: The job_id of this FilesSingleAllOfAttributes [Optional].
        file: The file of this FilesSingleAllOfAttributes [Optional].
    """

    number_of_files: Optional[int] = Field(alias="numberOfFiles", default=None)
    job_ref: Optional[str] = Field(alias="jobRef", default=None)
    job_id: Optional[str] = Field(alias="jobId", default=None)
    file: Optional[List[FileSingle]] = Field(alias="File", default=None)

FilesSingleAllOfAttributes.update_forward_refs()
