# coding: utf-8

from __future__ import annotations
from datetime import date, datetime  # noqa: F401

import re  # noqa: F401
from typing import Any, Dict, List, Optional  # noqa: F401

from pydantic import AnyUrl, BaseModel, EmailStr, Field, validator  # noqa: F401
from openapi_server.models.geographical_coordinates import GeographicalCoordinates


class GeoLoc(BaseModel):
    """NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).

    Do not edit the class manually.

    GeoLoc - a model defined in OpenAPI

        geographical_coordinates: The geographical_coordinates of this GeoLoc [Optional].
        civic_location: The civic_location of this GeoLoc [Optional].
    """

    geographical_coordinates: Optional[GeographicalCoordinates] = Field(alias="geographicalCoordinates", default=None)
    civic_location: Optional[str] = Field(alias="civicLocation", default=None)

GeoLoc.update_forward_refs()
