# coding: utf-8

from __future__ import annotations
from datetime import date, datetime  # noqa: F401

import re  # noqa: F401
from typing import Any, Dict, List, Optional  # noqa: F401

from pydantic import AnyUrl, BaseModel, EmailStr, Field, validator  # noqa: F401
from openapi_server.models.epe1_single import EPE1Single
from openapi_server.models.epf1_u_single import EPF1USingle
from openapi_server.models.epng_u_single import EPNgUSingle
from openapi_server.models.eps1_u_single import EPS1USingle
from openapi_server.models.epx2_u_single import EPX2USingle
from openapi_server.models.epxn_u_single import EPXnUSingle
from openapi_server.models.gnb_cu_up_function_single_all_of_attributes import GnbCuUpFunctionSingleAllOfAttributes
from openapi_server.models.managed_nf_service_single import ManagedNFServiceSingle
from openapi_server.models.perf_metric_job_single import PerfMetricJobSingle
from openapi_server.models.rrm_policy_ratio_single import RRMPolicyRatioSingle
from openapi_server.models.threshold_monitor_single import ThresholdMonitorSingle
from openapi_server.models.trace_job_single import TraceJobSingle
from openapi_server.models.vs_data_container_single import VsDataContainerSingle


class GnbCuUpFunctionSingle(BaseModel):
    """NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).

    Do not edit the class manually.

    GnbCuUpFunctionSingle - a model defined in OpenAPI

        id: The id of this GnbCuUpFunctionSingle.
        object_class: The object_class of this GnbCuUpFunctionSingle [Optional].
        object_instance: The object_instance of this GnbCuUpFunctionSingle [Optional].
        vs_data_container: The vs_data_container of this GnbCuUpFunctionSingle [Optional].
        attributes: The attributes of this GnbCuUpFunctionSingle [Optional].
        perf_metric_job: The perf_metric_job of this GnbCuUpFunctionSingle [Optional].
        threshold_monitor: The threshold_monitor of this GnbCuUpFunctionSingle [Optional].
        managed_nf_service: The managed_nf_service of this GnbCuUpFunctionSingle [Optional].
        trace_job: The trace_job of this GnbCuUpFunctionSingle [Optional].
        rrm_policy_ratio: The rrm_policy_ratio of this GnbCuUpFunctionSingle [Optional].
        ep_e1: The ep_e1 of this GnbCuUpFunctionSingle [Optional].
        ep_xn_u: The ep_xn_u of this GnbCuUpFunctionSingle [Optional].
        ep_f1_u: The ep_f1_u of this GnbCuUpFunctionSingle [Optional].
        ep_ng_u: The ep_ng_u of this GnbCuUpFunctionSingle [Optional].
        ep_x2_u: The ep_x2_u of this GnbCuUpFunctionSingle [Optional].
        ep_s1_u: The ep_s1_u of this GnbCuUpFunctionSingle [Optional].
    """

    id: str = Field(alias="id")
    object_class: Optional[str] = Field(alias="objectClass", default=None)
    object_instance: Optional[str] = Field(alias="objectInstance", default=None)
    vs_data_container: Optional[List[VsDataContainerSingle]] = Field(alias="VsDataContainer", default=None)
    attributes: Optional[GnbCuUpFunctionSingleAllOfAttributes] = Field(alias="attributes", default=None)
    perf_metric_job: Optional[List[PerfMetricJobSingle]] = Field(alias="PerfMetricJob", default=None)
    threshold_monitor: Optional[List[ThresholdMonitorSingle]] = Field(alias="ThresholdMonitor", default=None)
    managed_nf_service: Optional[List[ManagedNFServiceSingle]] = Field(alias="ManagedNFService", default=None)
    trace_job: Optional[List[TraceJobSingle]] = Field(alias="TraceJob", default=None)
    rrm_policy_ratio: Optional[List[RRMPolicyRatioSingle]] = Field(alias="RRMPolicyRatio", default=None)
    ep_e1: Optional[EPE1Single] = Field(alias="EP_E1", default=None)
    ep_xn_u: Optional[List[EPXnUSingle]] = Field(alias="EP_XnU", default=None)
    ep_f1_u: Optional[List[EPF1USingle]] = Field(alias="EP_F1U", default=None)
    ep_ng_u: Optional[List[EPNgUSingle]] = Field(alias="EP_NgU", default=None)
    ep_x2_u: Optional[List[EPX2USingle]] = Field(alias="EP_X2U", default=None)
    ep_s1_u: Optional[List[EPS1USingle]] = Field(alias="EP_S1U", default=None)

GnbCuUpFunctionSingle.update_forward_refs()
