# coding: utf-8

from __future__ import annotations
from datetime import date, datetime  # noqa: F401

import re  # noqa: F401
from typing import Any, Dict, List, Optional  # noqa: F401

from pydantic import AnyUrl, BaseModel, EmailStr, Field, validator  # noqa: F401
from openapi_server.models.fulfilment_info import FulfilmentInfo
from openapi_server.models.intent_context import IntentContext
from openapi_server.models.intent_single_all_of_intent_expectations_inner import IntentSingleAllOfIntentExpectationsInner
from openapi_server.models.vs_data_container_single import VsDataContainerSingle


class IntentSingle(BaseModel):
    """NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).

    Do not edit the class manually.

    IntentSingle - a model defined in OpenAPI

        id: The id of this IntentSingle.
        object_class: The object_class of this IntentSingle [Optional].
        object_instance: The object_instance of this IntentSingle [Optional].
        vs_data_container: The vs_data_container of this IntentSingle [Optional].
        user_label: The user_label of this IntentSingle [Optional].
        intent_expectations: The intent_expectations of this IntentSingle [Optional].
        intent_contexts: The intent_contexts of this IntentSingle [Optional].
        intent_fulfilment_info: The intent_fulfilment_info of this IntentSingle [Optional].
    """

    id: str = Field(alias="id")
    object_class: Optional[str] = Field(alias="objectClass", default=None)
    object_instance: Optional[str] = Field(alias="objectInstance", default=None)
    vs_data_container: Optional[List[VsDataContainerSingle]] = Field(alias="VsDataContainer", default=None)
    user_label: Optional[str] = Field(alias="userLabel", default=None)
    intent_expectations: Optional[List[IntentSingleAllOfIntentExpectationsInner]] = Field(alias="intentExpectations", default=None)
    intent_contexts: Optional[List[IntentContext]] = Field(alias="intentContexts", default=None)
    intent_fulfilment_info: Optional[FulfilmentInfo] = Field(alias="intentFulfilmentInfo", default=None)

IntentSingle.update_forward_refs()
