# coding: utf-8

from __future__ import annotations
from datetime import date, datetime  # noqa: F401

import re  # noqa: F401
from typing import Any, Dict, List, Optional  # noqa: F401

from pydantic import AnyUrl, BaseModel, EmailStr, Field, validator  # noqa: F401
from openapi_server.models.expectation_verb import ExpectationVerb
from openapi_server.models.fulfilment_info import FulfilmentInfo
from openapi_server.models.intent_expectation import IntentExpectation
from openapi_server.models.radio_network_expectation import RadioNetworkExpectation
from openapi_server.models.service_support_expectation import ServiceSupportExpectation
from openapi_server.models.service_support_expectation_expectation_contexts_inner import ServiceSupportExpectationExpectationContextsInner
from openapi_server.models.service_support_expectation_expectation_targets_inner import ServiceSupportExpectationExpectationTargetsInner
from openapi_server.models.service_support_expectation_object import ServiceSupportExpectationObject


class IntentSingleAllOfIntentExpectationsInner(BaseModel):
    """NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).

    Do not edit the class manually.

    IntentSingleAllOfIntentExpectationsInner - a model defined in OpenAPI

        expectation_id: The expectation_id of this IntentSingleAllOfIntentExpectationsInner [Optional].
        expectation_verb: The expectation_verb of this IntentSingleAllOfIntentExpectationsInner [Optional].
        expectation_objects: The expectation_objects of this IntentSingleAllOfIntentExpectationsInner [Optional].
        expectation_targets: The expectation_targets of this IntentSingleAllOfIntentExpectationsInner [Optional].
        expectation_contexts: The expectation_contexts of this IntentSingleAllOfIntentExpectationsInner [Optional].
        expectationfulfilment_info: The expectationfulfilment_info of this IntentSingleAllOfIntentExpectationsInner [Optional].
    """

    expectation_id: Optional[str] = Field(alias="expectationId", default=None)
    expectation_verb: Optional[ExpectationVerb] = Field(alias="expectationVerb", default=None)
    expectation_objects: Optional[List[ServiceSupportExpectationObject]] = Field(alias="expectationObjects", default=None)
    expectation_targets: Optional[List[ServiceSupportExpectationExpectationTargetsInner]] = Field(alias="expectationTargets", default=None)
    expectation_contexts: Optional[List[ServiceSupportExpectationExpectationContextsInner]] = Field(alias="expectationContexts", default=None)
    expectationfulfilment_info: Optional[FulfilmentInfo] = Field(alias="expectationfulfilmentInfo", default=None)

IntentSingleAllOfIntentExpectationsInner.update_forward_refs()
