# coding: utf-8

from __future__ import annotations
from datetime import date, datetime  # noqa: F401

import re  # noqa: F401
from typing import Any, Dict, List, Optional  # noqa: F401

from pydantic import AnyUrl, BaseModel, EmailStr, Field, validator  # noqa: F401


class LowSINRContext(BaseModel):
    """NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).

    Do not edit the class manually.

    LowSINRContext - a model defined in OpenAPI

        context_attribute: The context_attribute of this LowSINRContext [Optional].
        context_condition: The context_condition of this LowSINRContext [Optional].
        context_value_range: The context_value_range of this LowSINRContext [Optional].
    """

    context_attribute: Optional[str] = Field(alias="contextAttribute", default=None)
    context_condition: Optional[str] = Field(alias="contextCondition", default=None)
    context_value_range: Optional[int] = Field(alias="contextValueRange", default=None)

LowSINRContext.update_forward_refs()
