# coding: utf-8

from __future__ import annotations
from datetime import date, datetime  # noqa: F401

import re  # noqa: F401
from typing import Any, Dict, List, Optional  # noqa: F401

from pydantic import AnyUrl, BaseModel, EmailStr, Field, validator  # noqa: F401
from openapi_server.models.supported_perf_metric_group import SupportedPerfMetricGroup


class ManagedElementSingle1AllOfAttributes(BaseModel):
    """NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).

    Do not edit the class manually.

    ManagedElementSingle1AllOfAttributes - a model defined in OpenAPI

        dn_prefix: The dn_prefix of this ManagedElementSingle1AllOfAttributes [Optional].
        managed_element_type_list: The managed_element_type_list of this ManagedElementSingle1AllOfAttributes [Optional].
        user_label: The user_label of this ManagedElementSingle1AllOfAttributes [Optional].
        location_name: The location_name of this ManagedElementSingle1AllOfAttributes [Optional].
        managed_by: The managed_by of this ManagedElementSingle1AllOfAttributes [Optional].
        vendor_name: The vendor_name of this ManagedElementSingle1AllOfAttributes [Optional].
        user_defined_state: The user_defined_state of this ManagedElementSingle1AllOfAttributes [Optional].
        sw_version: The sw_version of this ManagedElementSingle1AllOfAttributes [Optional].
        priority_label: The priority_label of this ManagedElementSingle1AllOfAttributes [Optional].
        supported_perf_metric_groups: The supported_perf_metric_groups of this ManagedElementSingle1AllOfAttributes [Optional].
        supported_trace_metrics: The supported_trace_metrics of this ManagedElementSingle1AllOfAttributes [Optional].
    """

    dn_prefix: Optional[str] = Field(alias="dnPrefix", default=None)
    managed_element_type_list: Optional[List[str]] = Field(alias="managedElementTypeList", default=None)
    user_label: Optional[str] = Field(alias="userLabel", default=None)
    location_name: Optional[str] = Field(alias="locationName", default=None)
    managed_by: Optional[List[str]] = Field(alias="managedBy", default=None)
    vendor_name: Optional[str] = Field(alias="vendorName", default=None)
    user_defined_state: Optional[str] = Field(alias="userDefinedState", default=None)
    sw_version: Optional[str] = Field(alias="swVersion", default=None)
    priority_label: Optional[int] = Field(alias="priorityLabel", default=None)
    supported_perf_metric_groups: Optional[List[SupportedPerfMetricGroup]] = Field(alias="supportedPerfMetricGroups", default=None)
    supported_trace_metrics: Optional[List[str]] = Field(alias="supportedTraceMetrics", default=None)

ManagedElementSingle1AllOfAttributes.update_forward_refs()
