# coding: utf-8

from __future__ import annotations
from datetime import date, datetime  # noqa: F401

import re  # noqa: F401
from typing import Any, Dict, List, Optional  # noqa: F401

from pydantic import AnyUrl, BaseModel, EmailStr, Field, validator  # noqa: F401
from openapi_server.models.snssai import Snssai


class NetworkSliceInfo(BaseModel):
    """NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).

    Do not edit the class manually.

    NetworkSliceInfo - a model defined in OpenAPI

        s_nssai: The s_nssai of this NetworkSliceInfo [Optional].
        c_nsiid: The c_nsiid of this NetworkSliceInfo [Optional].
        network_slice_ref: The network_slice_ref of this NetworkSliceInfo [Optional].
    """

    s_nssai: Optional[Snssai] = Field(alias="sNSSAI", default=None)
    c_nsiid: Optional[str] = Field(alias="cNSIId", default=None)
    network_slice_ref: Optional[List[str]] = Field(alias="networkSliceRef", default=None)

NetworkSliceInfo.update_forward_refs()
