# coding: utf-8

from __future__ import annotations
from datetime import date, datetime  # noqa: F401

import re  # noqa: F401
from typing import Any, Dict, List, Optional  # noqa: F401

from pydantic import AnyUrl, BaseModel, EmailStr, Field, validator  # noqa: F401
from openapi_server.models.notification_type import NotificationType


class NotificationHeader(BaseModel):
    """NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).

    Do not edit the class manually.

    NotificationHeader - a model defined in OpenAPI

        href: The href of this NotificationHeader.
        notification_id: The notification_id of this NotificationHeader.
        notification_type: The notification_type of this NotificationHeader.
        event_time: The event_time of this NotificationHeader.
        system_dn: The system_dn of this NotificationHeader.
    """

    href: str = Field(alias="href")
    notification_id: int = Field(alias="notificationId")
    notification_type: NotificationType = Field(alias="notificationType")
    event_time: datetime = Field(alias="eventTime")
    system_dn: str = Field(alias="systemDN")

NotificationHeader.update_forward_refs()
