# coding: utf-8

from __future__ import annotations
from datetime import date, datetime  # noqa: F401

import re  # noqa: F401
from typing import Any, Dict, List, Optional  # noqa: F401

from pydantic import AnyUrl, BaseModel, EmailStr, Field, validator  # noqa: F401


class NRTACRange(BaseModel):
    """NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).

    Do not edit the class manually.

    NRTACRange - a model defined in OpenAPI

        n_rta_cstart: The n_rta_cstart of this NRTACRange [Optional].
        n_rta_cend: The n_rta_cend of this NRTACRange [Optional].
        n_rta_cpattern: The n_rta_cpattern of this NRTACRange [Optional].
    """

    n_rta_cstart: Optional[str] = Field(alias="nRTACstart", default=None)
    n_rta_cend: Optional[str] = Field(alias="nRTACend", default=None)
    n_rta_cpattern: Optional[str] = Field(alias="nRTACpattern", default=None)

NRTACRange.update_forward_refs()
