# coding: utf-8

from __future__ import annotations
from datetime import date, datetime  # noqa: F401

import re  # noqa: F401
from typing import Any, Dict, List, Optional  # noqa: F401

from pydantic import AnyUrl, BaseModel, EmailStr, Field, validator  # noqa: F401
from openapi_server.models.patch_operation import PatchOperation


class PatchItem(BaseModel):
    """NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).

    Do not edit the class manually.

    PatchItem - a model defined in OpenAPI

        op: The op of this PatchItem [Optional].
        _from: The _from of this PatchItem [Optional].
        path: The path of this PatchItem [Optional].
        value: The value of this PatchItem [Optional].
    """

    op: Optional[PatchOperation] = Field(alias="op", default=None)
    _from: Optional[str] = Field(alias="from", default=None)
    path: Optional[str] = Field(alias="path", default=None)
    value: Optional[object] = Field(alias="value", default=None)

PatchItem.update_forward_refs()
