# coding: utf-8

from __future__ import annotations
from datetime import date, datetime  # noqa: F401

import re  # noqa: F401
from typing import Any, Dict, List, Optional  # noqa: F401

from pydantic import AnyUrl, BaseModel, EmailStr, Field, validator  # noqa: F401
from openapi_server.models.q_offset_range import QOffsetRange


class QOffsetRangeList(BaseModel):
    """NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).

    Do not edit the class manually.

    QOffsetRangeList - a model defined in OpenAPI

        rsrp_offset_ssb: The rsrp_offset_ssb of this QOffsetRangeList [Optional].
        rsrq_offset_ssb: The rsrq_offset_ssb of this QOffsetRangeList [Optional].
        sinr_offset_ssb: The sinr_offset_ssb of this QOffsetRangeList [Optional].
        rsrp_offset_csi_rs: The rsrp_offset_csi_rs of this QOffsetRangeList [Optional].
        rsrq_offset_csi_rs: The rsrq_offset_csi_rs of this QOffsetRangeList [Optional].
        sinr_offset_csi_rs: The sinr_offset_csi_rs of this QOffsetRangeList [Optional].
    """

    rsrp_offset_ssb: Optional[QOffsetRange] = Field(alias="rsrpOffsetSSB", default=None)
    rsrq_offset_ssb: Optional[QOffsetRange] = Field(alias="rsrqOffsetSSB", default=None)
    sinr_offset_ssb: Optional[QOffsetRange] = Field(alias="sinrOffsetSSB", default=None)
    rsrp_offset_csi_rs: Optional[QOffsetRange] = Field(alias="rsrpOffsetCSI-RS", default=None)
    rsrq_offset_csi_rs: Optional[QOffsetRange] = Field(alias="rsrqOffsetCSI-RS", default=None)
    sinr_offset_csi_rs: Optional[QOffsetRange] = Field(alias="sinrOffsetCSI-RS", default=None)

QOffsetRangeList.update_forward_refs()
