# coding: utf-8

from __future__ import annotations
from datetime import date, datetime  # noqa: F401

import re  # noqa: F401
from typing import Any, Dict, List, Optional  # noqa: F401

from pydantic import AnyUrl, BaseModel, EmailStr, Field, validator  # noqa: F401


class QFPacketDelayThresholdsType(BaseModel):
    """NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).

    Do not edit the class manually.

    QFPacketDelayThresholdsType - a model defined in OpenAPI

        threshold_dl: The threshold_dl of this QFPacketDelayThresholdsType [Optional].
        threshold_ul: The threshold_ul of this QFPacketDelayThresholdsType [Optional].
        threshold_rtt: The threshold_rtt of this QFPacketDelayThresholdsType [Optional].
    """

    threshold_dl: Optional[int] = Field(alias="thresholdDl", default=None)
    threshold_ul: Optional[int] = Field(alias="thresholdUl", default=None)
    threshold_rtt: Optional[int] = Field(alias="thresholdRtt", default=None)

QFPacketDelayThresholdsType.update_forward_refs()
