# coding: utf-8

from __future__ import annotations
from datetime import date, datetime  # noqa: F401

import re  # noqa: F401
from typing import Any, Dict, List, Optional  # noqa: F401

from pydantic import AnyUrl, BaseModel, EmailStr, Field, validator  # noqa: F401
from openapi_server.models.qf_packet_delay_thresholds_type import QFPacketDelayThresholdsType
from openapi_server.models.snssai import Snssai


class QFQoSMonitoringControlSingleAllOfAttributes(BaseModel):
    """NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).

    Do not edit the class manually.

    QFQoSMonitoringControlSingleAllOfAttributes - a model defined in OpenAPI

        q_fqo_s_monitoring_state: The q_fqo_s_monitoring_state of this QFQoSMonitoringControlSingleAllOfAttributes [Optional].
        q_f_monitored_snssais: The q_f_monitored_snssais of this QFQoSMonitoringControlSingleAllOfAttributes [Optional].
        q_f_monitored5_qis: The q_f_monitored5_qis of this QFQoSMonitoringControlSingleAllOfAttributes [Optional].
        is_event_triggered_qf_monitoring_supported: The is_event_triggered_qf_monitoring_supported of this QFQoSMonitoringControlSingleAllOfAttributes [Optional].
        is_periodic_qf_monitoring_supported: The is_periodic_qf_monitoring_supported of this QFQoSMonitoringControlSingleAllOfAttributes [Optional].
        is_session_released_qf_monitoring_supported: The is_session_released_qf_monitoring_supported of this QFQoSMonitoringControlSingleAllOfAttributes [Optional].
        q_f_packet_delay_thresholds: The q_f_packet_delay_thresholds of this QFQoSMonitoringControlSingleAllOfAttributes [Optional].
        q_f_minimum_wait_time: The q_f_minimum_wait_time of this QFQoSMonitoringControlSingleAllOfAttributes [Optional].
        q_f_measurement_period: The q_f_measurement_period of this QFQoSMonitoringControlSingleAllOfAttributes [Optional].
    """

    q_fqo_s_monitoring_state: Optional[str] = Field(alias="qFQoSMonitoringState", default=None)
    q_f_monitored_snssais: Optional[List[Snssai]] = Field(alias="qFMonitoredSNSSAIs", default=None)
    q_f_monitored5_qis: Optional[List[int]] = Field(alias="qFMonitored5QIs", default=None)
    is_event_triggered_qf_monitoring_supported: Optional[bool] = Field(alias="isEventTriggeredQFMonitoringSupported", default=None)
    is_periodic_qf_monitoring_supported: Optional[bool] = Field(alias="isPeriodicQFMonitoringSupported", default=None)
    is_session_released_qf_monitoring_supported: Optional[bool] = Field(alias="isSessionReleasedQFMonitoringSupported", default=None)
    q_f_packet_delay_thresholds: Optional[QFPacketDelayThresholdsType] = Field(alias="qFPacketDelayThresholds", default=None)
    q_f_minimum_wait_time: Optional[int] = Field(alias="qFMinimumWaitTime", default=None)
    q_f_measurement_period: Optional[int] = Field(alias="qFMeasurementPeriod", default=None)

QFQoSMonitoringControlSingleAllOfAttributes.update_forward_refs()
