# coding: utf-8

from __future__ import annotations
from datetime import date, datetime  # noqa: F401

import re  # noqa: F401
from typing import Any, Dict, List, Optional  # noqa: F401

from pydantic import AnyUrl, BaseModel, EmailStr, Field, validator  # noqa: F401
from openapi_server.models.radio_network_expectation_object_object_contexts_inner import RadioNetworkExpectationObjectObjectContextsInner


class RadioNetworkExpectationObject(BaseModel):
    """NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).

    Do not edit the class manually.

    RadioNetworkExpectationObject - a model defined in OpenAPI

        object_type: The object_type of this RadioNetworkExpectationObject [Optional].
        object_instance: The object_instance of this RadioNetworkExpectationObject [Optional].
        object_contexts: The object_contexts of this RadioNetworkExpectationObject [Optional].
    """

    object_type: Optional[str] = Field(alias="objectType", default=None)
    object_instance: Optional[str] = Field(alias="objectInstance", default=None)
    object_contexts: Optional[List[RadioNetworkExpectationObjectObjectContextsInner]] = Field(alias="objectContexts", default=None)

RadioNetworkExpectationObject.update_forward_refs()
