# coding: utf-8

from __future__ import annotations
from datetime import date, datetime  # noqa: F401

import re  # noqa: F401
from typing import Any, Dict, List, Optional  # noqa: F401

from pydantic import AnyUrl, BaseModel, EmailStr, Field, validator  # noqa: F401
from openapi_server.models.condition import Condition
from openapi_server.models.coverage_area_polygon_context import CoverageAreaPolygonContext
from openapi_server.models.coverage_tac_context import CoverageTACContext
from openapi_server.models.nrfq_band_context import NRFqBandContext
from openapi_server.models.object_context import ObjectContext
from openapi_server.models.plmn_context import PLMNContext
from openapi_server.models.rat_context import RATContext


class RadioNetworkExpectationObjectObjectContextsInner(BaseModel):
    """NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).

    Do not edit the class manually.

    RadioNetworkExpectationObjectObjectContextsInner - a model defined in OpenAPI

        context_attribute: The context_attribute of this RadioNetworkExpectationObjectObjectContextsInner [Optional].
        context_condition: The context_condition of this RadioNetworkExpectationObjectObjectContextsInner [Optional].
        context_value_range: The context_value_range of this RadioNetworkExpectationObjectObjectContextsInner [Optional].
    """

    context_attribute: Optional[str] = Field(alias="contextAttribute", default=None)
    context_condition: Optional[Condition] = Field(alias="contextCondition", default=None)
    context_value_range: Optional[List[float]] = Field(alias="contextValueRange", default=None)

RadioNetworkExpectationObjectObjectContextsInner.update_forward_refs()
