# coding: utf-8

from __future__ import annotations
from datetime import date, datetime  # noqa: F401

import re  # noqa: F401
from typing import Any, Dict, List, Optional  # noqa: F401

from pydantic import AnyUrl, BaseModel, EmailStr, Field, validator  # noqa: F401
from openapi_server.models.delay_tolerance import DelayTolerance
from openapi_server.models.deterministic_comm import DeterministicComm
from openapi_server.models.mobility_level import MobilityLevel
from openapi_server.models.positioning_ran_subnet import PositioningRANSubnet
from openapi_server.models.sharing_level import SharingLevel
from openapi_server.models.slice_simultaneous_use import SliceSimultaneousUse
from openapi_server.models.synchronicity_ran_subnet import SynchronicityRANSubnet
from openapi_server.models.term_density import TermDensity
from openapi_server.models.xl_thpt import XLThpt


class RANSliceSubnetProfile(BaseModel):
    """NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).

    Do not edit the class manually.

    RANSliceSubnetProfile - a model defined in OpenAPI

        coverage_area_ta_list: The coverage_area_ta_list of this RANSliceSubnetProfile [Optional].
        d_l_latency: The d_l_latency of this RANSliceSubnetProfile [Optional].
        u_l_latency: The u_l_latency of this RANSliceSubnetProfile [Optional].
        u_e_mobility_level: The u_e_mobility_level of this RANSliceSubnetProfile [Optional].
        resource_sharing_level: The resource_sharing_level of this RANSliceSubnetProfile [Optional].
        max_numberof_ues: The max_numberof_ues of this RANSliceSubnetProfile [Optional].
        activity_factor: The activity_factor of this RANSliceSubnetProfile [Optional].
        d_l_thpt_per_slice_subnet: The d_l_thpt_per_slice_subnet of this RANSliceSubnetProfile [Optional].
        d_l_thpt_per_ue: The d_l_thpt_per_ue of this RANSliceSubnetProfile [Optional].
        u_l_thpt_per_slice_subnet: The u_l_thpt_per_slice_subnet of this RANSliceSubnetProfile [Optional].
        u_l_thpt_per_ue: The u_l_thpt_per_ue of this RANSliceSubnetProfile [Optional].
        u_e_speed: The u_e_speed of this RANSliceSubnetProfile [Optional].
        reliability: The reliability of this RANSliceSubnetProfile [Optional].
        s_st: The s_st of this RANSliceSubnetProfile [Optional].
        d_l_max_pkt_size: The d_l_max_pkt_size of this RANSliceSubnetProfile [Optional].
        u_l_max_pkt_size: The u_l_max_pkt_size of this RANSliceSubnetProfile [Optional].
        n_r_operating_bands: The n_r_operating_bands of this RANSliceSubnetProfile [Optional].
        delay_tolerance: The delay_tolerance of this RANSliceSubnetProfile [Optional].
        positioning: The positioning of this RANSliceSubnetProfile [Optional].
        slice_simultaneous_use: The slice_simultaneous_use of this RANSliceSubnetProfile [Optional].
        energy_efficiency: The energy_efficiency of this RANSliceSubnetProfile [Optional].
        term_density: The term_density of this RANSliceSubnetProfile [Optional].
        survival_time: The survival_time of this RANSliceSubnetProfile [Optional].
        synchronicity: The synchronicity of this RANSliceSubnetProfile [Optional].
        d_l_deterministic_comm: The d_l_deterministic_comm of this RANSliceSubnetProfile [Optional].
        u_l_deterministic_comm: The u_l_deterministic_comm of this RANSliceSubnetProfile [Optional].
    """

    coverage_area_ta_list: Optional[List[int]] = Field(alias="coverageAreaTAList", default=None)
    d_l_latency: Optional[float] = Field(alias="dLLatency", default=None)
    u_l_latency: Optional[float] = Field(alias="uLLatency", default=None)
    u_e_mobility_level: Optional[MobilityLevel] = Field(alias="uEMobilityLevel", default=None)
    resource_sharing_level: Optional[SharingLevel] = Field(alias="resourceSharingLevel", default=None)
    max_numberof_ues: Optional[int] = Field(alias="maxNumberofUEs", default=None)
    activity_factor: Optional[int] = Field(alias="activityFactor", default=None)
    d_l_thpt_per_slice_subnet: Optional[XLThpt] = Field(alias="dLThptPerSliceSubnet", default=None)
    d_l_thpt_per_ue: Optional[XLThpt] = Field(alias="dLThptPerUE", default=None)
    u_l_thpt_per_slice_subnet: Optional[XLThpt] = Field(alias="uLThptPerSliceSubnet", default=None)
    u_l_thpt_per_ue: Optional[XLThpt] = Field(alias="uLThptPerUE", default=None)
    u_e_speed: Optional[int] = Field(alias="uESpeed", default=None)
    reliability: Optional[float] = Field(alias="reliability", default=None)
    s_st: Optional[int] = Field(alias="sST", default=None)
    d_l_max_pkt_size: Optional[int] = Field(alias="dLMaxPktSize", default=None)
    u_l_max_pkt_size: Optional[int] = Field(alias="uLMaxPktSize", default=None)
    n_r_operating_bands: Optional[str] = Field(alias="nROperatingBands", default=None)
    delay_tolerance: Optional[DelayTolerance] = Field(alias="delayTolerance", default=None)
    positioning: Optional[PositioningRANSubnet] = Field(alias="positioning", default=None)
    slice_simultaneous_use: Optional[SliceSimultaneousUse] = Field(alias="sliceSimultaneousUse", default=None)
    energy_efficiency: Optional[float] = Field(alias="energyEfficiency", default=None)
    term_density: Optional[TermDensity] = Field(alias="termDensity", default=None)
    survival_time: Optional[float] = Field(alias="survivalTime", default=None)
    synchronicity: Optional[SynchronicityRANSubnet] = Field(alias="synchronicity", default=None)
    d_l_deterministic_comm: Optional[DeterministicComm] = Field(alias="dLDeterministicComm", default=None)
    u_l_deterministic_comm: Optional[DeterministicComm] = Field(alias="uLDeterministicComm", default=None)

    @validator("s_st")
    def s_st_max(cls, value):
        assert value <= 255
        return value

RANSliceSubnetProfile.update_forward_refs()
