# coding: utf-8

from __future__ import annotations
from datetime import date, datetime  # noqa: F401

import re  # noqa: F401
from typing import Any, Dict, List, Optional  # noqa: F401

from pydantic import AnyUrl, BaseModel, EmailStr, Field, validator  # noqa: F401


class ReportingCtrlOneOf(BaseModel):
    """NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).

    Do not edit the class manually.

    ReportingCtrlOneOf - a model defined in OpenAPI

        file_reporting_period: The file_reporting_period of this ReportingCtrlOneOf [Optional].
    """

    file_reporting_period: Optional[int] = Field(alias="fileReportingPeriod", default=None)

ReportingCtrlOneOf.update_forward_refs()
