# coding: utf-8

from __future__ import annotations
from datetime import date, datetime  # noqa: F401

import re  # noqa: F401
from typing import Any, Dict, List, Optional  # noqa: F401

from pydantic import AnyUrl, BaseModel, EmailStr, Field, validator  # noqa: F401


class RRMPolicyRatioSingleAllOfAttributesAllOf(BaseModel):
    """NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).

    Do not edit the class manually.

    RRMPolicyRatioSingleAllOfAttributesAllOf - a model defined in OpenAPI

        r_rm_policy_max_ratio: The r_rm_policy_max_ratio of this RRMPolicyRatioSingleAllOfAttributesAllOf [Optional].
        r_rm_policy_min_ratio: The r_rm_policy_min_ratio of this RRMPolicyRatioSingleAllOfAttributesAllOf [Optional].
        r_rm_policy_dedicated_ratio: The r_rm_policy_dedicated_ratio of this RRMPolicyRatioSingleAllOfAttributesAllOf [Optional].
    """

    r_rm_policy_max_ratio: Optional[int] = Field(alias="rRMPolicyMaxRatio", default=None)
    r_rm_policy_min_ratio: Optional[int] = Field(alias="rRMPolicyMinRatio", default=None)
    r_rm_policy_dedicated_ratio: Optional[int] = Field(alias="rRMPolicyDedicatedRatio", default=None)

RRMPolicyRatioSingleAllOfAttributesAllOf.update_forward_refs()
