# coding: utf-8

from __future__ import annotations
from datetime import date, datetime  # noqa: F401

import re  # noqa: F401
from typing import Any, Dict, List, Optional  # noqa: F401

from pydantic import AnyUrl, BaseModel, EmailStr, Field, validator  # noqa: F401
from openapi_server.models.host_addr import HostAddr
from openapi_server.models.pee_parameter import PeeParameter
from openapi_server.models.supported_func import SupportedFunc
from openapi_server.models.supported_perf_metric_group import SupportedPerfMetricGroup
from openapi_server.models.vnf_parameter import VnfParameter


class ScpFunctionSingleAllOfAttributes(BaseModel):
    """NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).

    Do not edit the class manually.

    ScpFunctionSingleAllOfAttributes - a model defined in OpenAPI

        user_label: The user_label of this ScpFunctionSingleAllOfAttributes [Optional].
        vnf_parameters_list: The vnf_parameters_list of this ScpFunctionSingleAllOfAttributes [Optional].
        pee_parameters_list: The pee_parameters_list of this ScpFunctionSingleAllOfAttributes [Optional].
        priority_label: The priority_label of this ScpFunctionSingleAllOfAttributes [Optional].
        supported_perf_metric_groups: The supported_perf_metric_groups of this ScpFunctionSingleAllOfAttributes [Optional].
        supported_trace_metrics: The supported_trace_metrics of this ScpFunctionSingleAllOfAttributes [Optional].
        supported_func_list: The supported_func_list of this ScpFunctionSingleAllOfAttributes [Optional].
        address: The address of this ScpFunctionSingleAllOfAttributes [Optional].
    """

    user_label: Optional[str] = Field(alias="userLabel", default=None)
    vnf_parameters_list: Optional[List[VnfParameter]] = Field(alias="vnfParametersList", default=None)
    pee_parameters_list: Optional[List[PeeParameter]] = Field(alias="peeParametersList", default=None)
    priority_label: Optional[int] = Field(alias="priorityLabel", default=None)
    supported_perf_metric_groups: Optional[List[SupportedPerfMetricGroup]] = Field(alias="supportedPerfMetricGroups", default=None)
    supported_trace_metrics: Optional[List[str]] = Field(alias="supportedTraceMetrics", default=None)
    supported_func_list: Optional[List[SupportedFunc]] = Field(alias="supportedFuncList", default=None)
    address: Optional[HostAddr] = Field(alias="address", default=None)

ScpFunctionSingleAllOfAttributes.update_forward_refs()
