# coding: utf-8

from __future__ import annotations
from datetime import date, datetime  # noqa: F401

import re  # noqa: F401
from typing import Any, Dict, List, Optional  # noqa: F401

from pydantic import AnyUrl, BaseModel, EmailStr, Field, validator  # noqa: F401
from openapi_server.models.cn_slice_subnet_profile import CNSliceSubnetProfile
from openapi_server.models.plmn_info import PlmnInfo
from openapi_server.models.ran_slice_subnet_profile import RANSliceSubnetProfile
from openapi_server.models.top_slice_subnet_profile import TopSliceSubnetProfile


class SliceProfile(BaseModel):
    """NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).

    Do not edit the class manually.

    SliceProfile - a model defined in OpenAPI

        service_profile_id: The service_profile_id of this SliceProfile [Optional].
        plmn_info_list: The plmn_info_list of this SliceProfile [Optional].
        c_n_slice_subnet_profile: The c_n_slice_subnet_profile of this SliceProfile [Optional].
        r_an_slice_subnet_profile: The r_an_slice_subnet_profile of this SliceProfile [Optional].
        top_slice_subnet_profile: The top_slice_subnet_profile of this SliceProfile [Optional].
    """

    service_profile_id: Optional[str] = Field(alias="serviceProfileId", default=None)
    plmn_info_list: Optional[List[PlmnInfo]] = Field(alias="plmnInfoList", default=None)
    c_n_slice_subnet_profile: Optional[CNSliceSubnetProfile] = Field(alias="cNSliceSubnetProfile", default=None)
    r_an_slice_subnet_profile: Optional[RANSliceSubnetProfile] = Field(alias="rANSliceSubnetProfile", default=None)
    top_slice_subnet_profile: Optional[TopSliceSubnetProfile] = Field(alias="topSliceSubnetProfile", default=None)

SliceProfile.update_forward_refs()
