# coding: utf-8

from __future__ import annotations
from datetime import date, datetime  # noqa: F401

import re  # noqa: F401
from typing import Any, Dict, List, Optional  # noqa: F401

from pydantic import AnyUrl, BaseModel, EmailStr, Field, validator  # noqa: F401
from openapi_server.models.administrative_state import AdministrativeState
from openapi_server.models.plmn_info import PlmnInfo


class SnssaiInfo(BaseModel):
    """NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).

    Do not edit the class manually.

    SnssaiInfo - a model defined in OpenAPI

        plmn_info: The plmn_info of this SnssaiInfo [Optional].
        administrative_state: The administrative_state of this SnssaiInfo [Optional].
    """

    plmn_info: Optional[PlmnInfo] = Field(alias="plmnInfo", default=None)
    administrative_state: Optional[AdministrativeState] = Field(alias="administrativeState", default=None)

SnssaiInfo.update_forward_refs()
