# coding: utf-8

from __future__ import annotations
from datetime import date, datetime  # noqa: F401

import re  # noqa: F401
from typing import Any, Dict, List, Optional  # noqa: F401

from pydantic import AnyUrl, BaseModel, EmailStr, Field, validator  # noqa: F401
from openapi_server.models.intent_single import IntentSingle
from openapi_server.models.sub_network_single import SubNetworkSingle


class SubNetworkSingle4AllOf(BaseModel):
    """NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).

    Do not edit the class manually.

    SubNetworkSingle4AllOf - a model defined in OpenAPI

        sub_network: The sub_network of this SubNetworkSingle4AllOf [Optional].
        intent: The intent of this SubNetworkSingle4AllOf [Optional].
    """

    sub_network: Optional[List[SubNetworkSingle]] = Field(alias="SubNetwork", default=None)
    intent: Optional[List[IntentSingle]] = Field(alias="Intent", default=None)

SubNetworkSingle4AllOf.update_forward_refs()
