# coding: utf-8

from __future__ import annotations
from datetime import date, datetime  # noqa: F401

import re  # noqa: F401
from typing import Any, Dict, List, Optional  # noqa: F401

from pydantic import AnyUrl, BaseModel, EmailStr, Field, validator  # noqa: F401


class SupportedPerfMetricGroup(BaseModel):
    """NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).

    Do not edit the class manually.

    SupportedPerfMetricGroup - a model defined in OpenAPI

        performance_metrics: The performance_metrics of this SupportedPerfMetricGroup [Optional].
        granularity_periods: The granularity_periods of this SupportedPerfMetricGroup [Optional].
        reporting_methods: The reporting_methods of this SupportedPerfMetricGroup [Optional].
        reporting_periods: The reporting_periods of this SupportedPerfMetricGroup [Optional].
    """

    performance_metrics: Optional[List[str]] = Field(alias="performanceMetrics", default=None)
    granularity_periods: Optional[List[int]] = Field(alias="granularityPeriods", default=None)
    reporting_methods: Optional[List[str]] = Field(alias="reportingMethods", default=None)
    reporting_periods: Optional[List[int]] = Field(alias="reportingPeriods", default=None)

SupportedPerfMetricGroup.update_forward_refs()
