# coding: utf-8

from __future__ import annotations
from datetime import date, datetime  # noqa: F401

import re  # noqa: F401
from typing import Any, Dict, List, Optional  # noqa: F401

from pydantic import AnyUrl, BaseModel, EmailStr, Field, validator  # noqa: F401
from openapi_server.models.threshold_info_hysteresis import ThresholdInfoHysteresis
from openapi_server.models.threshold_info_threshold_value import ThresholdInfoThresholdValue


class ThresholdInfo(BaseModel):
    """NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).

    Do not edit the class manually.

    ThresholdInfo - a model defined in OpenAPI

        threshold_direction: The threshold_direction of this ThresholdInfo [Optional].
        threshold_value: The threshold_value of this ThresholdInfo [Optional].
        hysteresis: The hysteresis of this ThresholdInfo [Optional].
    """

    threshold_direction: Optional[str] = Field(alias="thresholdDirection", default=None)
    threshold_value: Optional[ThresholdInfoThresholdValue] = Field(alias="thresholdValue", default=None)
    hysteresis: Optional[ThresholdInfoHysteresis] = Field(alias="hysteresis", default=None)

ThresholdInfo.update_forward_refs()
