# coding: utf-8

from __future__ import annotations
from datetime import date, datetime  # noqa: F401

import re  # noqa: F401
from typing import Any, Dict, List, Optional  # noqa: F401

from pydantic import AnyUrl, BaseModel, EmailStr, Field, validator  # noqa: F401


class TraceReferenceType(BaseModel):
    """NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).

    Do not edit the class manually.

    TraceReferenceType - a model defined in OpenAPI

        mcc: The mcc of this TraceReferenceType.
        mnc: The mnc of this TraceReferenceType.
        trace_id: The trace_id of this TraceReferenceType.
    """

    mcc: str = Field(alias="mcc")
    mnc: str = Field(alias="mnc")
    trace_id: str = Field(alias="traceId")

    @validator("mcc")
    def mcc_pattern(cls, value):
        assert value is not None and re.match(r"^[0-9]{3}$", value)
        return value

    @validator("mnc")
    def mnc_pattern(cls, value):
        assert value is not None and re.match(r"^[0-9]{2,3}$", value)
        return value

TraceReferenceType.update_forward_refs()
