# coding: utf-8

from __future__ import annotations
from datetime import date, datetime  # noqa: F401

import re  # noqa: F401
from typing import Any, Dict, List, Optional  # noqa: F401

from pydantic import AnyUrl, BaseModel, EmailStr, Field, validator  # noqa: F401


class TraceTargetType(BaseModel):
    """NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).

    Do not edit the class manually.

    TraceTargetType - a model defined in OpenAPI

        target_id_type: The target_id_type of this TraceTargetType.
        target_id_value: The target_id_value of this TraceTargetType.
    """

    target_id_type: str = Field(alias="TargetIdType")
    target_id_value: str = Field(alias="TargetIdValue")

TraceTargetType.update_forward_refs()
