# coding: utf-8

from __future__ import annotations
from datetime import date, datetime  # noqa: F401

import re  # noqa: F401
from typing import Any, Dict, List, Optional  # noqa: F401

from pydantic import AnyUrl, BaseModel, EmailStr, Field, validator  # noqa: F401


class UeAccProbilityDist(BaseModel):
    """NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).

    Do not edit the class manually.

    UeAccProbilityDist - a model defined in OpenAPI

        target_probability: The target_probability of this UeAccProbilityDist [Optional].
        numberofpreamblessent: The numberofpreamblessent of this UeAccProbilityDist [Optional].
    """

    target_probability: Optional[int] = Field(alias="targetProbability", default=None)
    numberofpreamblessent: Optional[int] = Field(alias="numberofpreamblessent", default=None)

UeAccProbilityDist.update_forward_refs()
