# coding: utf-8

from __future__ import annotations
from datetime import date, datetime  # noqa: F401

import re  # noqa: F401
from typing import Any, Dict, List, Optional  # noqa: F401

from pydantic import AnyUrl, BaseModel, EmailStr, Field, validator  # noqa: F401


class VsDataContainerSingleAttributes(BaseModel):
    """NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).

    Do not edit the class manually.

    VsDataContainerSingleAttributes - a model defined in OpenAPI

        vs_data_type: The vs_data_type of this VsDataContainerSingleAttributes [Optional].
        vs_data_format_version: The vs_data_format_version of this VsDataContainerSingleAttributes [Optional].
        vs_data: The vs_data of this VsDataContainerSingleAttributes [Optional].
    """

    vs_data_type: Optional[str] = Field(alias="vsDataType", default=None)
    vs_data_format_version: Optional[str] = Field(alias="vsDataFormatVersion", default=None)
    vs_data: Optional[object] = Field(alias="vsData", default=None)

VsDataContainerSingleAttributes.update_forward_refs()
