# coding: utf-8

"""
    Provisioning MnS

    OAS 3.0.1 definition of the Provisioning MnS Â© 2022, 3GPP Organizational Partners (ARIB, ATIS, CCSA, ETSI, TSDSI, TTA, TTC). All rights reserved.  # noqa: E501

    The version of the OpenAPI document: 17.2.0
    Generated by: https://openapi-generator.tech
"""

from datetime import date, datetime  # noqa: F401
import decimal  # noqa: F401
import functools  # noqa: F401
import io  # noqa: F401
import re  # noqa: F401
import typing  # noqa: F401
import typing_extensions  # noqa: F401
import uuid  # noqa: F401

import frozendict  # noqa: F401

from openapi_client import schemas  # noqa: F401


class BwpSingle(
    schemas.ComposedSchema,
):
    """NOTE: This class is auto generated by OpenAPI Generator.
    Ref: https://openapi-generator.tech

    Do not edit the class manually.
    """


    class MetaOapg:
        
        
        class all_of_1(
            schemas.DictSchema
        ):
        
        
            class MetaOapg:
                
                class properties:
                    
                    
                    class attributes(
                        schemas.ComposedSchema,
                    ):
                    
                    
                        class MetaOapg:
                            
                            
                            class all_of_1(
                                schemas.DictSchema
                            ):
                            
                            
                                class MetaOapg:
                                    
                                    class properties:
                                    
                                        @staticmethod
                                        def bwpContext() -> typing.Type['BwpContext']:
                                            return BwpContext
                                    
                                        @staticmethod
                                        def isInitialBwp() -> typing.Type['IsInitialBwp']:
                                            return IsInitialBwp
                                        subCarrierSpacing = schemas.IntSchema
                                    
                                        @staticmethod
                                        def cyclicPrefix() -> typing.Type['CyclicPrefix']:
                                            return CyclicPrefix
                                        startRB = schemas.IntSchema
                                        numberOfRBs = schemas.IntSchema
                                        __annotations__ = {
                                            "bwpContext": bwpContext,
                                            "isInitialBwp": isInitialBwp,
                                            "subCarrierSpacing": subCarrierSpacing,
                                            "cyclicPrefix": cyclicPrefix,
                                            "startRB": startRB,
                                            "numberOfRBs": numberOfRBs,
                                        }
                                
                                @typing.overload
                                def __getitem__(self, name: typing_extensions.Literal["bwpContext"]) -> 'BwpContext': ...
                                
                                @typing.overload
                                def __getitem__(self, name: typing_extensions.Literal["isInitialBwp"]) -> 'IsInitialBwp': ...
                                
                                @typing.overload
                                def __getitem__(self, name: typing_extensions.Literal["subCarrierSpacing"]) -> MetaOapg.properties.subCarrierSpacing: ...
                                
                                @typing.overload
                                def __getitem__(self, name: typing_extensions.Literal["cyclicPrefix"]) -> 'CyclicPrefix': ...
                                
                                @typing.overload
                                def __getitem__(self, name: typing_extensions.Literal["startRB"]) -> MetaOapg.properties.startRB: ...
                                
                                @typing.overload
                                def __getitem__(self, name: typing_extensions.Literal["numberOfRBs"]) -> MetaOapg.properties.numberOfRBs: ...
                                
                                @typing.overload
                                def __getitem__(self, name: str) -> schemas.UnsetAnyTypeSchema: ...
                                
                                def __getitem__(self, name: typing.Union[typing_extensions.Literal["bwpContext", "isInitialBwp", "subCarrierSpacing", "cyclicPrefix", "startRB", "numberOfRBs", ], str]):
                                    # dict_instance[name] accessor
                                    return super().__getitem__(name)
                                
                                
                                @typing.overload
                                def get_item_oapg(self, name: typing_extensions.Literal["bwpContext"]) -> typing.Union['BwpContext', schemas.Unset]: ...
                                
                                @typing.overload
                                def get_item_oapg(self, name: typing_extensions.Literal["isInitialBwp"]) -> typing.Union['IsInitialBwp', schemas.Unset]: ...
                                
                                @typing.overload
                                def get_item_oapg(self, name: typing_extensions.Literal["subCarrierSpacing"]) -> typing.Union[MetaOapg.properties.subCarrierSpacing, schemas.Unset]: ...
                                
                                @typing.overload
                                def get_item_oapg(self, name: typing_extensions.Literal["cyclicPrefix"]) -> typing.Union['CyclicPrefix', schemas.Unset]: ...
                                
                                @typing.overload
                                def get_item_oapg(self, name: typing_extensions.Literal["startRB"]) -> typing.Union[MetaOapg.properties.startRB, schemas.Unset]: ...
                                
                                @typing.overload
                                def get_item_oapg(self, name: typing_extensions.Literal["numberOfRBs"]) -> typing.Union[MetaOapg.properties.numberOfRBs, schemas.Unset]: ...
                                
                                @typing.overload
                                def get_item_oapg(self, name: str) -> typing.Union[schemas.UnsetAnyTypeSchema, schemas.Unset]: ...
                                
                                def get_item_oapg(self, name: typing.Union[typing_extensions.Literal["bwpContext", "isInitialBwp", "subCarrierSpacing", "cyclicPrefix", "startRB", "numberOfRBs", ], str]):
                                    return super().get_item_oapg(name)
                                
                            
                                def __new__(
                                    cls,
                                    *_args: typing.Union[dict, frozendict.frozendict, ],
                                    bwpContext: typing.Union['BwpContext', schemas.Unset] = schemas.unset,
                                    isInitialBwp: typing.Union['IsInitialBwp', schemas.Unset] = schemas.unset,
                                    subCarrierSpacing: typing.Union[MetaOapg.properties.subCarrierSpacing, decimal.Decimal, int, schemas.Unset] = schemas.unset,
                                    cyclicPrefix: typing.Union['CyclicPrefix', schemas.Unset] = schemas.unset,
                                    startRB: typing.Union[MetaOapg.properties.startRB, decimal.Decimal, int, schemas.Unset] = schemas.unset,
                                    numberOfRBs: typing.Union[MetaOapg.properties.numberOfRBs, decimal.Decimal, int, schemas.Unset] = schemas.unset,
                                    _configuration: typing.Optional[schemas.Configuration] = None,
                                    **kwargs: typing.Union[schemas.AnyTypeSchema, dict, frozendict.frozendict, str, date, datetime, uuid.UUID, int, float, decimal.Decimal, None, list, tuple, bytes],
                                ) -> 'all_of_1':
                                    return super().__new__(
                                        cls,
                                        *_args,
                                        bwpContext=bwpContext,
                                        isInitialBwp=isInitialBwp,
                                        subCarrierSpacing=subCarrierSpacing,
                                        cyclicPrefix=cyclicPrefix,
                                        startRB=startRB,
                                        numberOfRBs=numberOfRBs,
                                        _configuration=_configuration,
                                        **kwargs,
                                    )
                            
                            @classmethod
                            @functools.lru_cache()
                            def all_of(cls):
                                # we need this here to make our import statements work
                                # we must store _composed_schemas in here so the code is only run
                                # when we invoke this method. If we kept this at the class
                                # level we would get an error because the class level
                                # code would be run when this module is imported, and these composed
                                # classes don't exist yet because their module has not finished
                                # loading
                                return [
                                    ManagedFunctionAttr,
                                    cls.all_of_1,
                                ]
                    
                    
                        def __new__(
                            cls,
                            *_args: typing.Union[dict, frozendict.frozendict, str, date, datetime, uuid.UUID, int, float, decimal.Decimal, bool, None, list, tuple, bytes, io.FileIO, io.BufferedReader, ],
                            _configuration: typing.Optional[schemas.Configuration] = None,
                            **kwargs: typing.Union[schemas.AnyTypeSchema, dict, frozendict.frozendict, str, date, datetime, uuid.UUID, int, float, decimal.Decimal, None, list, tuple, bytes],
                        ) -> 'attributes':
                            return super().__new__(
                                cls,
                                *_args,
                                _configuration=_configuration,
                                **kwargs,
                            )
                    __annotations__ = {
                        "attributes": attributes,
                    }
            
            @typing.overload
            def __getitem__(self, name: typing_extensions.Literal["attributes"]) -> MetaOapg.properties.attributes: ...
            
            @typing.overload
            def __getitem__(self, name: str) -> schemas.UnsetAnyTypeSchema: ...
            
            def __getitem__(self, name: typing.Union[typing_extensions.Literal["attributes", ], str]):
                # dict_instance[name] accessor
                return super().__getitem__(name)
            
            
            @typing.overload
            def get_item_oapg(self, name: typing_extensions.Literal["attributes"]) -> typing.Union[MetaOapg.properties.attributes, schemas.Unset]: ...
            
            @typing.overload
            def get_item_oapg(self, name: str) -> typing.Union[schemas.UnsetAnyTypeSchema, schemas.Unset]: ...
            
            def get_item_oapg(self, name: typing.Union[typing_extensions.Literal["attributes", ], str]):
                return super().get_item_oapg(name)
            
        
            def __new__(
                cls,
                *_args: typing.Union[dict, frozendict.frozendict, ],
                attributes: typing.Union[MetaOapg.properties.attributes, dict, frozendict.frozendict, str, date, datetime, uuid.UUID, int, float, decimal.Decimal, bool, None, list, tuple, bytes, io.FileIO, io.BufferedReader, schemas.Unset] = schemas.unset,
                _configuration: typing.Optional[schemas.Configuration] = None,
                **kwargs: typing.Union[schemas.AnyTypeSchema, dict, frozendict.frozendict, str, date, datetime, uuid.UUID, int, float, decimal.Decimal, None, list, tuple, bytes],
            ) -> 'all_of_1':
                return super().__new__(
                    cls,
                    *_args,
                    attributes=attributes,
                    _configuration=_configuration,
                    **kwargs,
                )
        
        @classmethod
        @functools.lru_cache()
        def all_of(cls):
            # we need this here to make our import statements work
            # we must store _composed_schemas in here so the code is only run
            # when we invoke this method. If we kept this at the class
            # level we would get an error because the class level
            # code would be run when this module is imported, and these composed
            # classes don't exist yet because their module has not finished
            # loading
            return [
                Top,
                cls.all_of_1,
                ManagedFunctionNcO,
            ]


    def __new__(
        cls,
        *_args: typing.Union[dict, frozendict.frozendict, str, date, datetime, uuid.UUID, int, float, decimal.Decimal, bool, None, list, tuple, bytes, io.FileIO, io.BufferedReader, ],
        _configuration: typing.Optional[schemas.Configuration] = None,
        **kwargs: typing.Union[schemas.AnyTypeSchema, dict, frozendict.frozendict, str, date, datetime, uuid.UUID, int, float, decimal.Decimal, None, list, tuple, bytes],
    ) -> 'BwpSingle':
        return super().__new__(
            cls,
            *_args,
            _configuration=_configuration,
            **kwargs,
        )

from openapi_client.model.bwp_context import BwpContext
from openapi_client.model.cyclic_prefix import CyclicPrefix
from openapi_client.model.is_initial_bwp import IsInitialBwp
from openapi_client.model.managed_function_attr import ManagedFunctionAttr
from openapi_client.model.managed_function_nc_o import ManagedFunctionNcO
from openapi_client.model.top import Top
