# coding: utf-8

"""
    Provisioning MnS

    OAS 3.0.1 definition of the Provisioning MnS Â© 2022, 3GPP Organizational Partners (ARIB, ATIS, CCSA, ETSI, TSDSI, TTA, TTC). All rights reserved.  # noqa: E501

    The version of the OpenAPI document: 17.2.0
    Generated by: https://openapi-generator.tech
"""

from datetime import date, datetime  # noqa: F401
import decimal  # noqa: F401
import functools  # noqa: F401
import io  # noqa: F401
import re  # noqa: F401
import typing  # noqa: F401
import typing_extensions  # noqa: F401
import uuid  # noqa: F401

import frozendict  # noqa: F401

from openapi_client import schemas  # noqa: F401


class CommModelType(
    schemas.EnumBase,
    schemas.StrSchema
):
    """NOTE: This class is auto generated by OpenAPI Generator.
    Ref: https://openapi-generator.tech

    Do not edit the class manually.

    any of enumrated value
    """


    class MetaOapg:
        enum_value_to_name = {
            "DIRECT_COMMUNICATION_WO_NRF": "DIRECT_COMMUNICATION_WO_NRF",
            "DIRECT_COMMUNICATION_WITH_NRF": "DIRECT_COMMUNICATION_WITH_NRF",
            "INDIRECT_COMMUNICATION_WO_DEDICATED_DISCOVERY": "INDIRECT_COMMUNICATION_WO_DEDICATED_DISCOVERY",
            "INDIRECT_COMMUNICATION_WITH_DEDICATED_DISCOVERY": "INDIRECT_COMMUNICATION_WITH_DEDICATED_DISCOVERY",
        }
    
    @schemas.classproperty
    def DIRECT_COMMUNICATION_WO_NRF(cls):
        return cls("DIRECT_COMMUNICATION_WO_NRF")
    
    @schemas.classproperty
    def DIRECT_COMMUNICATION_WITH_NRF(cls):
        return cls("DIRECT_COMMUNICATION_WITH_NRF")
    
    @schemas.classproperty
    def INDIRECT_COMMUNICATION_WO_DEDICATED_DISCOVERY(cls):
        return cls("INDIRECT_COMMUNICATION_WO_DEDICATED_DISCOVERY")
    
    @schemas.classproperty
    def INDIRECT_COMMUNICATION_WITH_DEDICATED_DISCOVERY(cls):
        return cls("INDIRECT_COMMUNICATION_WITH_DEDICATED_DISCOVERY")
