# coding: utf-8

"""
    Provisioning MnS

    OAS 3.0.1 definition of the Provisioning MnS Â© 2022, 3GPP Organizational Partners (ARIB, ATIS, CCSA, ETSI, TSDSI, TTA, TTC). All rights reserved.  # noqa: E501

    The version of the OpenAPI document: 17.2.0
    Generated by: https://openapi-generator.tech
"""

from datetime import date, datetime  # noqa: F401
import decimal  # noqa: F401
import functools  # noqa: F401
import io  # noqa: F401
import re  # noqa: F401
import typing  # noqa: F401
import typing_extensions  # noqa: F401
import uuid  # noqa: F401

import frozendict  # noqa: F401

from openapi_client import schemas  # noqa: F401


class EPN32Single(
    schemas.ComposedSchema,
):
    """NOTE: This class is auto generated by OpenAPI Generator.
    Ref: https://openapi-generator.tech

    Do not edit the class manually.
    """


    class MetaOapg:
        
        
        class all_of_1(
            schemas.DictSchema
        ):
        
        
            class MetaOapg:
                
                class properties:
                    
                    
                    class attributes(
                        schemas.ComposedSchema,
                    ):
                    
                    
                        class MetaOapg:
                            
                            
                            class all_of_1(
                                schemas.DictSchema
                            ):
                            
                            
                                class MetaOapg:
                                    
                                    class properties:
                                    
                                        @staticmethod
                                        def remotePlmnId() -> typing.Type['PlmnId']:
                                            return PlmnId
                                    
                                        @staticmethod
                                        def remoteSeppAddress() -> typing.Type['HostAddr']:
                                            return HostAddr
                                        remoteSeppId = schemas.IntSchema
                                        n32cParas = schemas.StrSchema
                                        n32fPolicy = schemas.StrSchema
                                        withIPX = schemas.BoolSchema
                                        __annotations__ = {
                                            "remotePlmnId": remotePlmnId,
                                            "remoteSeppAddress": remoteSeppAddress,
                                            "remoteSeppId": remoteSeppId,
                                            "n32cParas": n32cParas,
                                            "n32fPolicy": n32fPolicy,
                                            "withIPX": withIPX,
                                        }
                                
                                @typing.overload
                                def __getitem__(self, name: typing_extensions.Literal["remotePlmnId"]) -> 'PlmnId': ...
                                
                                @typing.overload
                                def __getitem__(self, name: typing_extensions.Literal["remoteSeppAddress"]) -> 'HostAddr': ...
                                
                                @typing.overload
                                def __getitem__(self, name: typing_extensions.Literal["remoteSeppId"]) -> MetaOapg.properties.remoteSeppId: ...
                                
                                @typing.overload
                                def __getitem__(self, name: typing_extensions.Literal["n32cParas"]) -> MetaOapg.properties.n32cParas: ...
                                
                                @typing.overload
                                def __getitem__(self, name: typing_extensions.Literal["n32fPolicy"]) -> MetaOapg.properties.n32fPolicy: ...
                                
                                @typing.overload
                                def __getitem__(self, name: typing_extensions.Literal["withIPX"]) -> MetaOapg.properties.withIPX: ...
                                
                                @typing.overload
                                def __getitem__(self, name: str) -> schemas.UnsetAnyTypeSchema: ...
                                
                                def __getitem__(self, name: typing.Union[typing_extensions.Literal["remotePlmnId", "remoteSeppAddress", "remoteSeppId", "n32cParas", "n32fPolicy", "withIPX", ], str]):
                                    # dict_instance[name] accessor
                                    return super().__getitem__(name)
                                
                                
                                @typing.overload
                                def get_item_oapg(self, name: typing_extensions.Literal["remotePlmnId"]) -> typing.Union['PlmnId', schemas.Unset]: ...
                                
                                @typing.overload
                                def get_item_oapg(self, name: typing_extensions.Literal["remoteSeppAddress"]) -> typing.Union['HostAddr', schemas.Unset]: ...
                                
                                @typing.overload
                                def get_item_oapg(self, name: typing_extensions.Literal["remoteSeppId"]) -> typing.Union[MetaOapg.properties.remoteSeppId, schemas.Unset]: ...
                                
                                @typing.overload
                                def get_item_oapg(self, name: typing_extensions.Literal["n32cParas"]) -> typing.Union[MetaOapg.properties.n32cParas, schemas.Unset]: ...
                                
                                @typing.overload
                                def get_item_oapg(self, name: typing_extensions.Literal["n32fPolicy"]) -> typing.Union[MetaOapg.properties.n32fPolicy, schemas.Unset]: ...
                                
                                @typing.overload
                                def get_item_oapg(self, name: typing_extensions.Literal["withIPX"]) -> typing.Union[MetaOapg.properties.withIPX, schemas.Unset]: ...
                                
                                @typing.overload
                                def get_item_oapg(self, name: str) -> typing.Union[schemas.UnsetAnyTypeSchema, schemas.Unset]: ...
                                
                                def get_item_oapg(self, name: typing.Union[typing_extensions.Literal["remotePlmnId", "remoteSeppAddress", "remoteSeppId", "n32cParas", "n32fPolicy", "withIPX", ], str]):
                                    return super().get_item_oapg(name)
                                
                            
                                def __new__(
                                    cls,
                                    *_args: typing.Union[dict, frozendict.frozendict, ],
                                    remotePlmnId: typing.Union['PlmnId', schemas.Unset] = schemas.unset,
                                    remoteSeppAddress: typing.Union['HostAddr', schemas.Unset] = schemas.unset,
                                    remoteSeppId: typing.Union[MetaOapg.properties.remoteSeppId, decimal.Decimal, int, schemas.Unset] = schemas.unset,
                                    n32cParas: typing.Union[MetaOapg.properties.n32cParas, str, schemas.Unset] = schemas.unset,
                                    n32fPolicy: typing.Union[MetaOapg.properties.n32fPolicy, str, schemas.Unset] = schemas.unset,
                                    withIPX: typing.Union[MetaOapg.properties.withIPX, bool, schemas.Unset] = schemas.unset,
                                    _configuration: typing.Optional[schemas.Configuration] = None,
                                    **kwargs: typing.Union[schemas.AnyTypeSchema, dict, frozendict.frozendict, str, date, datetime, uuid.UUID, int, float, decimal.Decimal, None, list, tuple, bytes],
                                ) -> 'all_of_1':
                                    return super().__new__(
                                        cls,
                                        *_args,
                                        remotePlmnId=remotePlmnId,
                                        remoteSeppAddress=remoteSeppAddress,
                                        remoteSeppId=remoteSeppId,
                                        n32cParas=n32cParas,
                                        n32fPolicy=n32fPolicy,
                                        withIPX=withIPX,
                                        _configuration=_configuration,
                                        **kwargs,
                                    )
                            
                            @classmethod
                            @functools.lru_cache()
                            def all_of(cls):
                                # we need this here to make our import statements work
                                # we must store _composed_schemas in here so the code is only run
                                # when we invoke this method. If we kept this at the class
                                # level we would get an error because the class level
                                # code would be run when this module is imported, and these composed
                                # classes don't exist yet because their module has not finished
                                # loading
                                return [
                                    EPRPAttr,
                                    cls.all_of_1,
                                ]
                    
                    
                        def __new__(
                            cls,
                            *_args: typing.Union[dict, frozendict.frozendict, str, date, datetime, uuid.UUID, int, float, decimal.Decimal, bool, None, list, tuple, bytes, io.FileIO, io.BufferedReader, ],
                            _configuration: typing.Optional[schemas.Configuration] = None,
                            **kwargs: typing.Union[schemas.AnyTypeSchema, dict, frozendict.frozendict, str, date, datetime, uuid.UUID, int, float, decimal.Decimal, None, list, tuple, bytes],
                        ) -> 'attributes':
                            return super().__new__(
                                cls,
                                *_args,
                                _configuration=_configuration,
                                **kwargs,
                            )
                    __annotations__ = {
                        "attributes": attributes,
                    }
            
            @typing.overload
            def __getitem__(self, name: typing_extensions.Literal["attributes"]) -> MetaOapg.properties.attributes: ...
            
            @typing.overload
            def __getitem__(self, name: str) -> schemas.UnsetAnyTypeSchema: ...
            
            def __getitem__(self, name: typing.Union[typing_extensions.Literal["attributes", ], str]):
                # dict_instance[name] accessor
                return super().__getitem__(name)
            
            
            @typing.overload
            def get_item_oapg(self, name: typing_extensions.Literal["attributes"]) -> typing.Union[MetaOapg.properties.attributes, schemas.Unset]: ...
            
            @typing.overload
            def get_item_oapg(self, name: str) -> typing.Union[schemas.UnsetAnyTypeSchema, schemas.Unset]: ...
            
            def get_item_oapg(self, name: typing.Union[typing_extensions.Literal["attributes", ], str]):
                return super().get_item_oapg(name)
            
        
            def __new__(
                cls,
                *_args: typing.Union[dict, frozendict.frozendict, ],
                attributes: typing.Union[MetaOapg.properties.attributes, dict, frozendict.frozendict, str, date, datetime, uuid.UUID, int, float, decimal.Decimal, bool, None, list, tuple, bytes, io.FileIO, io.BufferedReader, schemas.Unset] = schemas.unset,
                _configuration: typing.Optional[schemas.Configuration] = None,
                **kwargs: typing.Union[schemas.AnyTypeSchema, dict, frozendict.frozendict, str, date, datetime, uuid.UUID, int, float, decimal.Decimal, None, list, tuple, bytes],
            ) -> 'all_of_1':
                return super().__new__(
                    cls,
                    *_args,
                    attributes=attributes,
                    _configuration=_configuration,
                    **kwargs,
                )
        
        @classmethod
        @functools.lru_cache()
        def all_of(cls):
            # we need this here to make our import statements work
            # we must store _composed_schemas in here so the code is only run
            # when we invoke this method. If we kept this at the class
            # level we would get an error because the class level
            # code would be run when this module is imported, and these composed
            # classes don't exist yet because their module has not finished
            # loading
            return [
                Top,
                cls.all_of_1,
            ]


    def __new__(
        cls,
        *_args: typing.Union[dict, frozendict.frozendict, str, date, datetime, uuid.UUID, int, float, decimal.Decimal, bool, None, list, tuple, bytes, io.FileIO, io.BufferedReader, ],
        _configuration: typing.Optional[schemas.Configuration] = None,
        **kwargs: typing.Union[schemas.AnyTypeSchema, dict, frozendict.frozendict, str, date, datetime, uuid.UUID, int, float, decimal.Decimal, None, list, tuple, bytes],
    ) -> 'EPN32Single':
        return super().__new__(
            cls,
            *_args,
            _configuration=_configuration,
            **kwargs,
        )

from openapi_client.model.eprp_attr import EPRPAttr
from openapi_client.model.host_addr import HostAddr
from openapi_client.model.plmn_id import PlmnId
from openapi_client.model.top import Top
