# coding: utf-8

"""
    Provisioning MnS

    OAS 3.0.1 definition of the Provisioning MnS Â© 2022, 3GPP Organizational Partners (ARIB, ATIS, CCSA, ETSI, TSDSI, TTA, TTC). All rights reserved.  # noqa: E501

    The version of the OpenAPI document: 17.2.0
    Generated by: https://openapi-generator.tech
"""

from datetime import date, datetime  # noqa: F401
import decimal  # noqa: F401
import functools  # noqa: F401
import io  # noqa: F401
import re  # noqa: F401
import typing  # noqa: F401
import typing_extensions  # noqa: F401
import uuid  # noqa: F401

import frozendict  # noqa: F401

from openapi_client import schemas  # noqa: F401


class GnbDuFunctionSingle(
    schemas.ComposedSchema,
):
    """NOTE: This class is auto generated by OpenAPI Generator.
    Ref: https://openapi-generator.tech

    Do not edit the class manually.
    """


    class MetaOapg:
        
        
        class all_of_1(
            schemas.DictSchema
        ):
        
        
            class MetaOapg:
                
                class properties:
                    
                    
                    class attributes(
                        schemas.ComposedSchema,
                    ):
                    
                    
                        class MetaOapg:
                            
                            
                            class all_of_1(
                                schemas.DictSchema
                            ):
                            
                            
                                class MetaOapg:
                                    
                                    class properties:
                                    
                                        @staticmethod
                                        def gnbDuId() -> typing.Type['GnbDuId']:
                                            return GnbDuId
                                    
                                        @staticmethod
                                        def gnbDuName() -> typing.Type['GnbName']:
                                            return GnbName
                                        gnbId = schemas.StrSchema
                                    
                                        @staticmethod
                                        def gnbIdLength() -> typing.Type['GnbIdLength']:
                                            return GnbIdLength
                                    
                                        @staticmethod
                                        def rimRSReportConf() -> typing.Type['RimRSReportConf']:
                                            return RimRSReportConf
                                        __annotations__ = {
                                            "gnbDuId": gnbDuId,
                                            "gnbDuName": gnbDuName,
                                            "gnbId": gnbId,
                                            "gnbIdLength": gnbIdLength,
                                            "rimRSReportConf": rimRSReportConf,
                                        }
                                
                                @typing.overload
                                def __getitem__(self, name: typing_extensions.Literal["gnbDuId"]) -> 'GnbDuId': ...
                                
                                @typing.overload
                                def __getitem__(self, name: typing_extensions.Literal["gnbDuName"]) -> 'GnbName': ...
                                
                                @typing.overload
                                def __getitem__(self, name: typing_extensions.Literal["gnbId"]) -> MetaOapg.properties.gnbId: ...
                                
                                @typing.overload
                                def __getitem__(self, name: typing_extensions.Literal["gnbIdLength"]) -> 'GnbIdLength': ...
                                
                                @typing.overload
                                def __getitem__(self, name: typing_extensions.Literal["rimRSReportConf"]) -> 'RimRSReportConf': ...
                                
                                @typing.overload
                                def __getitem__(self, name: str) -> schemas.UnsetAnyTypeSchema: ...
                                
                                def __getitem__(self, name: typing.Union[typing_extensions.Literal["gnbDuId", "gnbDuName", "gnbId", "gnbIdLength", "rimRSReportConf", ], str]):
                                    # dict_instance[name] accessor
                                    return super().__getitem__(name)
                                
                                
                                @typing.overload
                                def get_item_oapg(self, name: typing_extensions.Literal["gnbDuId"]) -> typing.Union['GnbDuId', schemas.Unset]: ...
                                
                                @typing.overload
                                def get_item_oapg(self, name: typing_extensions.Literal["gnbDuName"]) -> typing.Union['GnbName', schemas.Unset]: ...
                                
                                @typing.overload
                                def get_item_oapg(self, name: typing_extensions.Literal["gnbId"]) -> typing.Union[MetaOapg.properties.gnbId, schemas.Unset]: ...
                                
                                @typing.overload
                                def get_item_oapg(self, name: typing_extensions.Literal["gnbIdLength"]) -> typing.Union['GnbIdLength', schemas.Unset]: ...
                                
                                @typing.overload
                                def get_item_oapg(self, name: typing_extensions.Literal["rimRSReportConf"]) -> typing.Union['RimRSReportConf', schemas.Unset]: ...
                                
                                @typing.overload
                                def get_item_oapg(self, name: str) -> typing.Union[schemas.UnsetAnyTypeSchema, schemas.Unset]: ...
                                
                                def get_item_oapg(self, name: typing.Union[typing_extensions.Literal["gnbDuId", "gnbDuName", "gnbId", "gnbIdLength", "rimRSReportConf", ], str]):
                                    return super().get_item_oapg(name)
                                
                            
                                def __new__(
                                    cls,
                                    *_args: typing.Union[dict, frozendict.frozendict, ],
                                    gnbDuId: typing.Union['GnbDuId', schemas.Unset] = schemas.unset,
                                    gnbDuName: typing.Union['GnbName', schemas.Unset] = schemas.unset,
                                    gnbId: typing.Union[MetaOapg.properties.gnbId, str, schemas.Unset] = schemas.unset,
                                    gnbIdLength: typing.Union['GnbIdLength', schemas.Unset] = schemas.unset,
                                    rimRSReportConf: typing.Union['RimRSReportConf', schemas.Unset] = schemas.unset,
                                    _configuration: typing.Optional[schemas.Configuration] = None,
                                    **kwargs: typing.Union[schemas.AnyTypeSchema, dict, frozendict.frozendict, str, date, datetime, uuid.UUID, int, float, decimal.Decimal, None, list, tuple, bytes],
                                ) -> 'all_of_1':
                                    return super().__new__(
                                        cls,
                                        *_args,
                                        gnbDuId=gnbDuId,
                                        gnbDuName=gnbDuName,
                                        gnbId=gnbId,
                                        gnbIdLength=gnbIdLength,
                                        rimRSReportConf=rimRSReportConf,
                                        _configuration=_configuration,
                                        **kwargs,
                                    )
                            
                            @classmethod
                            @functools.lru_cache()
                            def all_of(cls):
                                # we need this here to make our import statements work
                                # we must store _composed_schemas in here so the code is only run
                                # when we invoke this method. If we kept this at the class
                                # level we would get an error because the class level
                                # code would be run when this module is imported, and these composed
                                # classes don't exist yet because their module has not finished
                                # loading
                                return [
                                    ManagedFunctionAttr,
                                    cls.all_of_1,
                                ]
                    
                    
                        def __new__(
                            cls,
                            *_args: typing.Union[dict, frozendict.frozendict, str, date, datetime, uuid.UUID, int, float, decimal.Decimal, bool, None, list, tuple, bytes, io.FileIO, io.BufferedReader, ],
                            _configuration: typing.Optional[schemas.Configuration] = None,
                            **kwargs: typing.Union[schemas.AnyTypeSchema, dict, frozendict.frozendict, str, date, datetime, uuid.UUID, int, float, decimal.Decimal, None, list, tuple, bytes],
                        ) -> 'attributes':
                            return super().__new__(
                                cls,
                                *_args,
                                _configuration=_configuration,
                                **kwargs,
                            )
                    __annotations__ = {
                        "attributes": attributes,
                    }
            
            @typing.overload
            def __getitem__(self, name: typing_extensions.Literal["attributes"]) -> MetaOapg.properties.attributes: ...
            
            @typing.overload
            def __getitem__(self, name: str) -> schemas.UnsetAnyTypeSchema: ...
            
            def __getitem__(self, name: typing.Union[typing_extensions.Literal["attributes", ], str]):
                # dict_instance[name] accessor
                return super().__getitem__(name)
            
            
            @typing.overload
            def get_item_oapg(self, name: typing_extensions.Literal["attributes"]) -> typing.Union[MetaOapg.properties.attributes, schemas.Unset]: ...
            
            @typing.overload
            def get_item_oapg(self, name: str) -> typing.Union[schemas.UnsetAnyTypeSchema, schemas.Unset]: ...
            
            def get_item_oapg(self, name: typing.Union[typing_extensions.Literal["attributes", ], str]):
                return super().get_item_oapg(name)
            
        
            def __new__(
                cls,
                *_args: typing.Union[dict, frozendict.frozendict, ],
                attributes: typing.Union[MetaOapg.properties.attributes, dict, frozendict.frozendict, str, date, datetime, uuid.UUID, int, float, decimal.Decimal, bool, None, list, tuple, bytes, io.FileIO, io.BufferedReader, schemas.Unset] = schemas.unset,
                _configuration: typing.Optional[schemas.Configuration] = None,
                **kwargs: typing.Union[schemas.AnyTypeSchema, dict, frozendict.frozendict, str, date, datetime, uuid.UUID, int, float, decimal.Decimal, None, list, tuple, bytes],
            ) -> 'all_of_1':
                return super().__new__(
                    cls,
                    *_args,
                    attributes=attributes,
                    _configuration=_configuration,
                    **kwargs,
                )
        
        
        class all_of_3(
            schemas.DictSchema
        ):
        
        
            class MetaOapg:
                
                class properties:
                
                    @staticmethod
                    def RRMPolicyRatio() -> typing.Type['RRMPolicyRatioMultiple']:
                        return RRMPolicyRatioMultiple
                
                    @staticmethod
                    def NrCellDu() -> typing.Type['NrCellDuMultiple']:
                        return NrCellDuMultiple
                
                    @staticmethod
                    def bwp_multiple() -> typing.Type['BwpMultiple']:
                        return BwpMultiple
                
                    @staticmethod
                    def nr_sector_carrier_multiple() -> typing.Type['NrSectorCarrierMultiple']:
                        return NrSectorCarrierMultiple
                
                    @staticmethod
                    def EP_F1C() -> typing.Type['EPF1CSingle']:
                        return EPF1CSingle
                
                    @staticmethod
                    def EP_F1U() -> typing.Type['EPF1UMultiple']:
                        return EPF1UMultiple
                
                    @staticmethod
                    def DRACHOptimizationFunction() -> typing.Type['DRACHOptimizationFunctionSingle']:
                        return DRACHOptimizationFunctionSingle
                
                    @staticmethod
                    def OperatorDU() -> typing.Type['OperatorDuMultiple']:
                        return OperatorDuMultiple
                    __annotations__ = {
                        "RRMPolicyRatio": RRMPolicyRatio,
                        "NrCellDu": NrCellDu,
                        "Bwp-Multiple": bwp_multiple,
                        "NrSectorCarrier-Multiple": nr_sector_carrier_multiple,
                        "EP_F1C": EP_F1C,
                        "EP_F1U": EP_F1U,
                        "DRACHOptimizationFunction": DRACHOptimizationFunction,
                        "OperatorDU": OperatorDU,
                    }
            
            @typing.overload
            def __getitem__(self, name: typing_extensions.Literal["RRMPolicyRatio"]) -> 'RRMPolicyRatioMultiple': ...
            
            @typing.overload
            def __getitem__(self, name: typing_extensions.Literal["NrCellDu"]) -> 'NrCellDuMultiple': ...
            
            @typing.overload
            def __getitem__(self, name: typing_extensions.Literal["Bwp-Multiple"]) -> 'BwpMultiple': ...
            
            @typing.overload
            def __getitem__(self, name: typing_extensions.Literal["NrSectorCarrier-Multiple"]) -> 'NrSectorCarrierMultiple': ...
            
            @typing.overload
            def __getitem__(self, name: typing_extensions.Literal["EP_F1C"]) -> 'EPF1CSingle': ...
            
            @typing.overload
            def __getitem__(self, name: typing_extensions.Literal["EP_F1U"]) -> 'EPF1UMultiple': ...
            
            @typing.overload
            def __getitem__(self, name: typing_extensions.Literal["DRACHOptimizationFunction"]) -> 'DRACHOptimizationFunctionSingle': ...
            
            @typing.overload
            def __getitem__(self, name: typing_extensions.Literal["OperatorDU"]) -> 'OperatorDuMultiple': ...
            
            @typing.overload
            def __getitem__(self, name: str) -> schemas.UnsetAnyTypeSchema: ...
            
            def __getitem__(self, name: typing.Union[typing_extensions.Literal["RRMPolicyRatio", "NrCellDu", "Bwp-Multiple", "NrSectorCarrier-Multiple", "EP_F1C", "EP_F1U", "DRACHOptimizationFunction", "OperatorDU", ], str]):
                # dict_instance[name] accessor
                return super().__getitem__(name)
            
            
            @typing.overload
            def get_item_oapg(self, name: typing_extensions.Literal["RRMPolicyRatio"]) -> typing.Union['RRMPolicyRatioMultiple', schemas.Unset]: ...
            
            @typing.overload
            def get_item_oapg(self, name: typing_extensions.Literal["NrCellDu"]) -> typing.Union['NrCellDuMultiple', schemas.Unset]: ...
            
            @typing.overload
            def get_item_oapg(self, name: typing_extensions.Literal["Bwp-Multiple"]) -> typing.Union['BwpMultiple', schemas.Unset]: ...
            
            @typing.overload
            def get_item_oapg(self, name: typing_extensions.Literal["NrSectorCarrier-Multiple"]) -> typing.Union['NrSectorCarrierMultiple', schemas.Unset]: ...
            
            @typing.overload
            def get_item_oapg(self, name: typing_extensions.Literal["EP_F1C"]) -> typing.Union['EPF1CSingle', schemas.Unset]: ...
            
            @typing.overload
            def get_item_oapg(self, name: typing_extensions.Literal["EP_F1U"]) -> typing.Union['EPF1UMultiple', schemas.Unset]: ...
            
            @typing.overload
            def get_item_oapg(self, name: typing_extensions.Literal["DRACHOptimizationFunction"]) -> typing.Union['DRACHOptimizationFunctionSingle', schemas.Unset]: ...
            
            @typing.overload
            def get_item_oapg(self, name: typing_extensions.Literal["OperatorDU"]) -> typing.Union['OperatorDuMultiple', schemas.Unset]: ...
            
            @typing.overload
            def get_item_oapg(self, name: str) -> typing.Union[schemas.UnsetAnyTypeSchema, schemas.Unset]: ...
            
            def get_item_oapg(self, name: typing.Union[typing_extensions.Literal["RRMPolicyRatio", "NrCellDu", "Bwp-Multiple", "NrSectorCarrier-Multiple", "EP_F1C", "EP_F1U", "DRACHOptimizationFunction", "OperatorDU", ], str]):
                return super().get_item_oapg(name)
            
        
            def __new__(
                cls,
                *_args: typing.Union[dict, frozendict.frozendict, ],
                RRMPolicyRatio: typing.Union['RRMPolicyRatioMultiple', schemas.Unset] = schemas.unset,
                NrCellDu: typing.Union['NrCellDuMultiple', schemas.Unset] = schemas.unset,
                EP_F1C: typing.Union['EPF1CSingle', schemas.Unset] = schemas.unset,
                EP_F1U: typing.Union['EPF1UMultiple', schemas.Unset] = schemas.unset,
                DRACHOptimizationFunction: typing.Union['DRACHOptimizationFunctionSingle', schemas.Unset] = schemas.unset,
                OperatorDU: typing.Union['OperatorDuMultiple', schemas.Unset] = schemas.unset,
                _configuration: typing.Optional[schemas.Configuration] = None,
                **kwargs: typing.Union[schemas.AnyTypeSchema, dict, frozendict.frozendict, str, date, datetime, uuid.UUID, int, float, decimal.Decimal, None, list, tuple, bytes],
            ) -> 'all_of_3':
                return super().__new__(
                    cls,
                    *_args,
                    RRMPolicyRatio=RRMPolicyRatio,
                    NrCellDu=NrCellDu,
                    EP_F1C=EP_F1C,
                    EP_F1U=EP_F1U,
                    DRACHOptimizationFunction=DRACHOptimizationFunction,
                    OperatorDU=OperatorDU,
                    _configuration=_configuration,
                    **kwargs,
                )
        
        @classmethod
        @functools.lru_cache()
        def all_of(cls):
            # we need this here to make our import statements work
            # we must store _composed_schemas in here so the code is only run
            # when we invoke this method. If we kept this at the class
            # level we would get an error because the class level
            # code would be run when this module is imported, and these composed
            # classes don't exist yet because their module has not finished
            # loading
            return [
                Top,
                cls.all_of_1,
                ManagedFunctionNcO,
                cls.all_of_3,
            ]


    def __new__(
        cls,
        *_args: typing.Union[dict, frozendict.frozendict, str, date, datetime, uuid.UUID, int, float, decimal.Decimal, bool, None, list, tuple, bytes, io.FileIO, io.BufferedReader, ],
        _configuration: typing.Optional[schemas.Configuration] = None,
        **kwargs: typing.Union[schemas.AnyTypeSchema, dict, frozendict.frozendict, str, date, datetime, uuid.UUID, int, float, decimal.Decimal, None, list, tuple, bytes],
    ) -> 'GnbDuFunctionSingle':
        return super().__new__(
            cls,
            *_args,
            _configuration=_configuration,
            **kwargs,
        )

from openapi_client.model.bwp_multiple import BwpMultiple
from openapi_client.model.drach_optimization_function_single import DRACHOptimizationFunctionSingle
from openapi_client.model.epf1_c_single import EPF1CSingle
from openapi_client.model.epf1_u_multiple import EPF1UMultiple
from openapi_client.model.gnb_du_id import GnbDuId
from openapi_client.model.gnb_id_length import GnbIdLength
from openapi_client.model.gnb_name import GnbName
from openapi_client.model.managed_function_attr import ManagedFunctionAttr
from openapi_client.model.managed_function_nc_o import ManagedFunctionNcO
from openapi_client.model.nr_cell_du_multiple import NrCellDuMultiple
from openapi_client.model.nr_sector_carrier_multiple import NrSectorCarrierMultiple
from openapi_client.model.operator_du_multiple import OperatorDuMultiple
from openapi_client.model.rim_rs_report_conf import RimRSReportConf
from openapi_client.model.rrm_policy_ratio_multiple import RRMPolicyRatioMultiple
from openapi_client.model.top import Top
