# coding: utf-8

"""
    Provisioning MnS

    OAS 3.0.1 definition of the Provisioning MnS Â© 2022, 3GPP Organizational Partners (ARIB, ATIS, CCSA, ETSI, TSDSI, TTA, TTC). All rights reserved.  # noqa: E501

    The version of the OpenAPI document: 17.2.0
    Generated by: https://openapi-generator.tech
"""

from datetime import date, datetime  # noqa: F401
import decimal  # noqa: F401
import functools  # noqa: F401
import io  # noqa: F401
import re  # noqa: F401
import typing  # noqa: F401
import typing_extensions  # noqa: F401
import uuid  # noqa: F401

import frozendict  # noqa: F401

from openapi_client import schemas  # noqa: F401


class ManagedFunctionNcO(
    schemas.DictSchema
):
    """NOTE: This class is auto generated by OpenAPI Generator.
    Ref: https://openapi-generator.tech

    Do not edit the class manually.
    """


    class MetaOapg:
        
        class properties:
        
            @staticmethod
            def PerfMetricJob() -> typing.Type['PerfMetricJobMultiple']:
                return PerfMetricJobMultiple
        
            @staticmethod
            def ThresholdMonitor() -> typing.Type['ThresholdMonitorMultiple']:
                return ThresholdMonitorMultiple
        
            @staticmethod
            def ManagedNFService() -> typing.Type['ManagedNFServiceMultiple']:
                return ManagedNFServiceMultiple
        
            @staticmethod
            def TraceJob() -> typing.Type['TraceJobMultiple']:
                return TraceJobMultiple
            __annotations__ = {
                "PerfMetricJob": PerfMetricJob,
                "ThresholdMonitor": ThresholdMonitor,
                "ManagedNFService": ManagedNFService,
                "TraceJob": TraceJob,
            }
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["PerfMetricJob"]) -> 'PerfMetricJobMultiple': ...
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["ThresholdMonitor"]) -> 'ThresholdMonitorMultiple': ...
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["ManagedNFService"]) -> 'ManagedNFServiceMultiple': ...
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["TraceJob"]) -> 'TraceJobMultiple': ...
    
    @typing.overload
    def __getitem__(self, name: str) -> schemas.UnsetAnyTypeSchema: ...
    
    def __getitem__(self, name: typing.Union[typing_extensions.Literal["PerfMetricJob", "ThresholdMonitor", "ManagedNFService", "TraceJob", ], str]):
        # dict_instance[name] accessor
        return super().__getitem__(name)
    
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["PerfMetricJob"]) -> typing.Union['PerfMetricJobMultiple', schemas.Unset]: ...
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["ThresholdMonitor"]) -> typing.Union['ThresholdMonitorMultiple', schemas.Unset]: ...
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["ManagedNFService"]) -> typing.Union['ManagedNFServiceMultiple', schemas.Unset]: ...
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["TraceJob"]) -> typing.Union['TraceJobMultiple', schemas.Unset]: ...
    
    @typing.overload
    def get_item_oapg(self, name: str) -> typing.Union[schemas.UnsetAnyTypeSchema, schemas.Unset]: ...
    
    def get_item_oapg(self, name: typing.Union[typing_extensions.Literal["PerfMetricJob", "ThresholdMonitor", "ManagedNFService", "TraceJob", ], str]):
        return super().get_item_oapg(name)
    

    def __new__(
        cls,
        *_args: typing.Union[dict, frozendict.frozendict, ],
        PerfMetricJob: typing.Union['PerfMetricJobMultiple', schemas.Unset] = schemas.unset,
        ThresholdMonitor: typing.Union['ThresholdMonitorMultiple', schemas.Unset] = schemas.unset,
        ManagedNFService: typing.Union['ManagedNFServiceMultiple', schemas.Unset] = schemas.unset,
        TraceJob: typing.Union['TraceJobMultiple', schemas.Unset] = schemas.unset,
        _configuration: typing.Optional[schemas.Configuration] = None,
        **kwargs: typing.Union[schemas.AnyTypeSchema, dict, frozendict.frozendict, str, date, datetime, uuid.UUID, int, float, decimal.Decimal, None, list, tuple, bytes],
    ) -> 'ManagedFunctionNcO':
        return super().__new__(
            cls,
            *_args,
            PerfMetricJob=PerfMetricJob,
            ThresholdMonitor=ThresholdMonitor,
            ManagedNFService=ManagedNFService,
            TraceJob=TraceJob,
            _configuration=_configuration,
            **kwargs,
        )

from openapi_client.model.managed_nf_service_multiple import ManagedNFServiceMultiple
from openapi_client.model.perf_metric_job_multiple import PerfMetricJobMultiple
from openapi_client.model.threshold_monitor_multiple import ThresholdMonitorMultiple
from openapi_client.model.trace_job_multiple import TraceJobMultiple
