# coding: utf-8

"""
    Provisioning MnS

    OAS 3.0.1 definition of the Provisioning MnS Â© 2022, 3GPP Organizational Partners (ARIB, ATIS, CCSA, ETSI, TSDSI, TTA, TTC). All rights reserved.  # noqa: E501

    The version of the OpenAPI document: 17.2.0
    Generated by: https://openapi-generator.tech
"""

from datetime import date, datetime  # noqa: F401
import decimal  # noqa: F401
import functools  # noqa: F401
import io  # noqa: F401
import re  # noqa: F401
import typing  # noqa: F401
import typing_extensions  # noqa: F401
import uuid  # noqa: F401

import frozendict  # noqa: F401

from openapi_client import schemas  # noqa: F401


class ManagementDataCollectionSingle(
    schemas.ComposedSchema,
):
    """NOTE: This class is auto generated by OpenAPI Generator.
    Ref: https://openapi-generator.tech

    Do not edit the class manually.
    """


    class MetaOapg:
        
        
        class all_of_1(
            schemas.DictSchema
        ):
        
        
            class MetaOapg:
                
                class properties:
                    
                    
                    class attributes(
                        schemas.DictSchema
                    ):
                    
                    
                        class MetaOapg:
                            
                            class properties:
                            
                                @staticmethod
                                def managementData() -> typing.Type['ManagementData']:
                                    return ManagementData
                            
                                @staticmethod
                                def targetNodeFilter() -> typing.Type['NodeFilter']:
                                    return NodeFilter
                            
                                @staticmethod
                                def collectionTimeWindow() -> typing.Type['TimeWindow']:
                                    return TimeWindow
                            
                                @staticmethod
                                def reportingCtrl() -> typing.Type['ReportingCtrl']:
                                    return ReportingCtrl
                                
                                
                                class dataScope(
                                    schemas.EnumBase,
                                    schemas.StrSchema
                                ):
                                    
                                    @schemas.classproperty
                                    def SNSSAI(cls):
                                        return cls("SNSSAI")
                                    
                                    @schemas.classproperty
                                    def QI(cls):
                                        return cls("5QI")
                                __annotations__ = {
                                    "managementData": managementData,
                                    "targetNodeFilter": targetNodeFilter,
                                    "collectionTimeWindow": collectionTimeWindow,
                                    "reportingCtrl": reportingCtrl,
                                    "dataScope": dataScope,
                                }
                        
                        @typing.overload
                        def __getitem__(self, name: typing_extensions.Literal["managementData"]) -> 'ManagementData': ...
                        
                        @typing.overload
                        def __getitem__(self, name: typing_extensions.Literal["targetNodeFilter"]) -> 'NodeFilter': ...
                        
                        @typing.overload
                        def __getitem__(self, name: typing_extensions.Literal["collectionTimeWindow"]) -> 'TimeWindow': ...
                        
                        @typing.overload
                        def __getitem__(self, name: typing_extensions.Literal["reportingCtrl"]) -> 'ReportingCtrl': ...
                        
                        @typing.overload
                        def __getitem__(self, name: typing_extensions.Literal["dataScope"]) -> MetaOapg.properties.dataScope: ...
                        
                        @typing.overload
                        def __getitem__(self, name: str) -> schemas.UnsetAnyTypeSchema: ...
                        
                        def __getitem__(self, name: typing.Union[typing_extensions.Literal["managementData", "targetNodeFilter", "collectionTimeWindow", "reportingCtrl", "dataScope", ], str]):
                            # dict_instance[name] accessor
                            return super().__getitem__(name)
                        
                        
                        @typing.overload
                        def get_item_oapg(self, name: typing_extensions.Literal["managementData"]) -> typing.Union['ManagementData', schemas.Unset]: ...
                        
                        @typing.overload
                        def get_item_oapg(self, name: typing_extensions.Literal["targetNodeFilter"]) -> typing.Union['NodeFilter', schemas.Unset]: ...
                        
                        @typing.overload
                        def get_item_oapg(self, name: typing_extensions.Literal["collectionTimeWindow"]) -> typing.Union['TimeWindow', schemas.Unset]: ...
                        
                        @typing.overload
                        def get_item_oapg(self, name: typing_extensions.Literal["reportingCtrl"]) -> typing.Union['ReportingCtrl', schemas.Unset]: ...
                        
                        @typing.overload
                        def get_item_oapg(self, name: typing_extensions.Literal["dataScope"]) -> typing.Union[MetaOapg.properties.dataScope, schemas.Unset]: ...
                        
                        @typing.overload
                        def get_item_oapg(self, name: str) -> typing.Union[schemas.UnsetAnyTypeSchema, schemas.Unset]: ...
                        
                        def get_item_oapg(self, name: typing.Union[typing_extensions.Literal["managementData", "targetNodeFilter", "collectionTimeWindow", "reportingCtrl", "dataScope", ], str]):
                            return super().get_item_oapg(name)
                        
                    
                        def __new__(
                            cls,
                            *_args: typing.Union[dict, frozendict.frozendict, ],
                            managementData: typing.Union['ManagementData', schemas.Unset] = schemas.unset,
                            targetNodeFilter: typing.Union['NodeFilter', schemas.Unset] = schemas.unset,
                            collectionTimeWindow: typing.Union['TimeWindow', schemas.Unset] = schemas.unset,
                            reportingCtrl: typing.Union['ReportingCtrl', schemas.Unset] = schemas.unset,
                            dataScope: typing.Union[MetaOapg.properties.dataScope, str, schemas.Unset] = schemas.unset,
                            _configuration: typing.Optional[schemas.Configuration] = None,
                            **kwargs: typing.Union[schemas.AnyTypeSchema, dict, frozendict.frozendict, str, date, datetime, uuid.UUID, int, float, decimal.Decimal, None, list, tuple, bytes],
                        ) -> 'attributes':
                            return super().__new__(
                                cls,
                                *_args,
                                managementData=managementData,
                                targetNodeFilter=targetNodeFilter,
                                collectionTimeWindow=collectionTimeWindow,
                                reportingCtrl=reportingCtrl,
                                dataScope=dataScope,
                                _configuration=_configuration,
                                **kwargs,
                            )
                    __annotations__ = {
                        "attributes": attributes,
                    }
            
            @typing.overload
            def __getitem__(self, name: typing_extensions.Literal["attributes"]) -> MetaOapg.properties.attributes: ...
            
            @typing.overload
            def __getitem__(self, name: str) -> schemas.UnsetAnyTypeSchema: ...
            
            def __getitem__(self, name: typing.Union[typing_extensions.Literal["attributes", ], str]):
                # dict_instance[name] accessor
                return super().__getitem__(name)
            
            
            @typing.overload
            def get_item_oapg(self, name: typing_extensions.Literal["attributes"]) -> typing.Union[MetaOapg.properties.attributes, schemas.Unset]: ...
            
            @typing.overload
            def get_item_oapg(self, name: str) -> typing.Union[schemas.UnsetAnyTypeSchema, schemas.Unset]: ...
            
            def get_item_oapg(self, name: typing.Union[typing_extensions.Literal["attributes", ], str]):
                return super().get_item_oapg(name)
            
        
            def __new__(
                cls,
                *_args: typing.Union[dict, frozendict.frozendict, ],
                attributes: typing.Union[MetaOapg.properties.attributes, dict, frozendict.frozendict, schemas.Unset] = schemas.unset,
                _configuration: typing.Optional[schemas.Configuration] = None,
                **kwargs: typing.Union[schemas.AnyTypeSchema, dict, frozendict.frozendict, str, date, datetime, uuid.UUID, int, float, decimal.Decimal, None, list, tuple, bytes],
            ) -> 'all_of_1':
                return super().__new__(
                    cls,
                    *_args,
                    attributes=attributes,
                    _configuration=_configuration,
                    **kwargs,
                )
        
        @classmethod
        @functools.lru_cache()
        def all_of(cls):
            # we need this here to make our import statements work
            # we must store _composed_schemas in here so the code is only run
            # when we invoke this method. If we kept this at the class
            # level we would get an error because the class level
            # code would be run when this module is imported, and these composed
            # classes don't exist yet because their module has not finished
            # loading
            return [
                Top,
                cls.all_of_1,
            ]


    def __new__(
        cls,
        *_args: typing.Union[dict, frozendict.frozendict, str, date, datetime, uuid.UUID, int, float, decimal.Decimal, bool, None, list, tuple, bytes, io.FileIO, io.BufferedReader, ],
        _configuration: typing.Optional[schemas.Configuration] = None,
        **kwargs: typing.Union[schemas.AnyTypeSchema, dict, frozendict.frozendict, str, date, datetime, uuid.UUID, int, float, decimal.Decimal, None, list, tuple, bytes],
    ) -> 'ManagementDataCollectionSingle':
        return super().__new__(
            cls,
            *_args,
            _configuration=_configuration,
            **kwargs,
        )

from openapi_client.model.management_data import ManagementData
from openapi_client.model.node_filter import NodeFilter
from openapi_client.model.reporting_ctrl import ReportingCtrl
from openapi_client.model.time_window import TimeWindow
from openapi_client.model.top import Top
