# coding: utf-8

"""
    Provisioning MnS

    OAS 3.0.1 definition of the Provisioning MnS Â© 2022, 3GPP Organizational Partners (ARIB, ATIS, CCSA, ETSI, TSDSI, TTA, TTC). All rights reserved.  # noqa: E501

    The version of the OpenAPI document: 17.2.0
    Generated by: https://openapi-generator.tech
"""

from datetime import date, datetime  # noqa: F401
import decimal  # noqa: F401
import functools  # noqa: F401
import io  # noqa: F401
import re  # noqa: F401
import typing  # noqa: F401
import typing_extensions  # noqa: F401
import uuid  # noqa: F401

import frozendict  # noqa: F401

from openapi_client import schemas  # noqa: F401


class MobilityLevel(
    schemas.EnumBase,
    schemas.StrSchema
):
    """NOTE: This class is auto generated by OpenAPI Generator.
    Ref: https://openapi-generator.tech

    Do not edit the class manually.
    """


    class MetaOapg:
        enum_value_to_name = {
            "STATIONARY": "STATIONARY",
            "NOMADIC": "NOMADIC",
            "RESTRICTED MOBILITY": "RESTRICTED_MOBILITY",
            "FULLY MOBILITY": "FULLY_MOBILITY",
        }
    
    @schemas.classproperty
    def STATIONARY(cls):
        return cls("STATIONARY")
    
    @schemas.classproperty
    def NOMADIC(cls):
        return cls("NOMADIC")
    
    @schemas.classproperty
    def RESTRICTED_MOBILITY(cls):
        return cls("RESTRICTED MOBILITY")
    
    @schemas.classproperty
    def FULLY_MOBILITY(cls):
        return cls("FULLY MOBILITY")
