# coding: utf-8

"""
    Provisioning MnS

    OAS 3.0.1 definition of the Provisioning MnS Â© 2022, 3GPP Organizational Partners (ARIB, ATIS, CCSA, ETSI, TSDSI, TTA, TTC). All rights reserved.  # noqa: E501

    The version of the OpenAPI document: 17.2.0
    Generated by: https://openapi-generator.tech
"""

from datetime import date, datetime  # noqa: F401
import decimal  # noqa: F401
import functools  # noqa: F401
import io  # noqa: F401
import re  # noqa: F401
import typing  # noqa: F401
import typing_extensions  # noqa: F401
import uuid  # noqa: F401

import frozendict  # noqa: F401

from openapi_client import schemas  # noqa: F401


class NrSectorCarrierSingle(
    schemas.ComposedSchema,
):
    """NOTE: This class is auto generated by OpenAPI Generator.
    Ref: https://openapi-generator.tech

    Do not edit the class manually.
    """


    class MetaOapg:
        
        
        class all_of_1(
            schemas.DictSchema
        ):
        
        
            class MetaOapg:
                
                class properties:
                    
                    
                    class attributes(
                        schemas.ComposedSchema,
                    ):
                    
                    
                        class MetaOapg:
                            
                            
                            class all_of_1(
                                schemas.DictSchema
                            ):
                            
                            
                                class MetaOapg:
                                    
                                    class properties:
                                    
                                        @staticmethod
                                        def txDirection() -> typing.Type['TxDirection']:
                                            return TxDirection
                                        configuredMaxTxPower = schemas.IntSchema
                                        arfcnDL = schemas.IntSchema
                                        arfcnUL = schemas.IntSchema
                                        bSChannelBwDL = schemas.IntSchema
                                        bSChannelBwUL = schemas.IntSchema
                                        sectorEquipmentFunctionRef = schemas.StrSchema
                                        __annotations__ = {
                                            "txDirection": txDirection,
                                            "configuredMaxTxPower": configuredMaxTxPower,
                                            "arfcnDL": arfcnDL,
                                            "arfcnUL": arfcnUL,
                                            "bSChannelBwDL": bSChannelBwDL,
                                            "bSChannelBwUL": bSChannelBwUL,
                                            "sectorEquipmentFunctionRef": sectorEquipmentFunctionRef,
                                        }
                                
                                @typing.overload
                                def __getitem__(self, name: typing_extensions.Literal["txDirection"]) -> 'TxDirection': ...
                                
                                @typing.overload
                                def __getitem__(self, name: typing_extensions.Literal["configuredMaxTxPower"]) -> MetaOapg.properties.configuredMaxTxPower: ...
                                
                                @typing.overload
                                def __getitem__(self, name: typing_extensions.Literal["arfcnDL"]) -> MetaOapg.properties.arfcnDL: ...
                                
                                @typing.overload
                                def __getitem__(self, name: typing_extensions.Literal["arfcnUL"]) -> MetaOapg.properties.arfcnUL: ...
                                
                                @typing.overload
                                def __getitem__(self, name: typing_extensions.Literal["bSChannelBwDL"]) -> MetaOapg.properties.bSChannelBwDL: ...
                                
                                @typing.overload
                                def __getitem__(self, name: typing_extensions.Literal["bSChannelBwUL"]) -> MetaOapg.properties.bSChannelBwUL: ...
                                
                                @typing.overload
                                def __getitem__(self, name: typing_extensions.Literal["sectorEquipmentFunctionRef"]) -> MetaOapg.properties.sectorEquipmentFunctionRef: ...
                                
                                @typing.overload
                                def __getitem__(self, name: str) -> schemas.UnsetAnyTypeSchema: ...
                                
                                def __getitem__(self, name: typing.Union[typing_extensions.Literal["txDirection", "configuredMaxTxPower", "arfcnDL", "arfcnUL", "bSChannelBwDL", "bSChannelBwUL", "sectorEquipmentFunctionRef", ], str]):
                                    # dict_instance[name] accessor
                                    return super().__getitem__(name)
                                
                                
                                @typing.overload
                                def get_item_oapg(self, name: typing_extensions.Literal["txDirection"]) -> typing.Union['TxDirection', schemas.Unset]: ...
                                
                                @typing.overload
                                def get_item_oapg(self, name: typing_extensions.Literal["configuredMaxTxPower"]) -> typing.Union[MetaOapg.properties.configuredMaxTxPower, schemas.Unset]: ...
                                
                                @typing.overload
                                def get_item_oapg(self, name: typing_extensions.Literal["arfcnDL"]) -> typing.Union[MetaOapg.properties.arfcnDL, schemas.Unset]: ...
                                
                                @typing.overload
                                def get_item_oapg(self, name: typing_extensions.Literal["arfcnUL"]) -> typing.Union[MetaOapg.properties.arfcnUL, schemas.Unset]: ...
                                
                                @typing.overload
                                def get_item_oapg(self, name: typing_extensions.Literal["bSChannelBwDL"]) -> typing.Union[MetaOapg.properties.bSChannelBwDL, schemas.Unset]: ...
                                
                                @typing.overload
                                def get_item_oapg(self, name: typing_extensions.Literal["bSChannelBwUL"]) -> typing.Union[MetaOapg.properties.bSChannelBwUL, schemas.Unset]: ...
                                
                                @typing.overload
                                def get_item_oapg(self, name: typing_extensions.Literal["sectorEquipmentFunctionRef"]) -> typing.Union[MetaOapg.properties.sectorEquipmentFunctionRef, schemas.Unset]: ...
                                
                                @typing.overload
                                def get_item_oapg(self, name: str) -> typing.Union[schemas.UnsetAnyTypeSchema, schemas.Unset]: ...
                                
                                def get_item_oapg(self, name: typing.Union[typing_extensions.Literal["txDirection", "configuredMaxTxPower", "arfcnDL", "arfcnUL", "bSChannelBwDL", "bSChannelBwUL", "sectorEquipmentFunctionRef", ], str]):
                                    return super().get_item_oapg(name)
                                
                            
                                def __new__(
                                    cls,
                                    *_args: typing.Union[dict, frozendict.frozendict, ],
                                    txDirection: typing.Union['TxDirection', schemas.Unset] = schemas.unset,
                                    configuredMaxTxPower: typing.Union[MetaOapg.properties.configuredMaxTxPower, decimal.Decimal, int, schemas.Unset] = schemas.unset,
                                    arfcnDL: typing.Union[MetaOapg.properties.arfcnDL, decimal.Decimal, int, schemas.Unset] = schemas.unset,
                                    arfcnUL: typing.Union[MetaOapg.properties.arfcnUL, decimal.Decimal, int, schemas.Unset] = schemas.unset,
                                    bSChannelBwDL: typing.Union[MetaOapg.properties.bSChannelBwDL, decimal.Decimal, int, schemas.Unset] = schemas.unset,
                                    bSChannelBwUL: typing.Union[MetaOapg.properties.bSChannelBwUL, decimal.Decimal, int, schemas.Unset] = schemas.unset,
                                    sectorEquipmentFunctionRef: typing.Union[MetaOapg.properties.sectorEquipmentFunctionRef, str, schemas.Unset] = schemas.unset,
                                    _configuration: typing.Optional[schemas.Configuration] = None,
                                    **kwargs: typing.Union[schemas.AnyTypeSchema, dict, frozendict.frozendict, str, date, datetime, uuid.UUID, int, float, decimal.Decimal, None, list, tuple, bytes],
                                ) -> 'all_of_1':
                                    return super().__new__(
                                        cls,
                                        *_args,
                                        txDirection=txDirection,
                                        configuredMaxTxPower=configuredMaxTxPower,
                                        arfcnDL=arfcnDL,
                                        arfcnUL=arfcnUL,
                                        bSChannelBwDL=bSChannelBwDL,
                                        bSChannelBwUL=bSChannelBwUL,
                                        sectorEquipmentFunctionRef=sectorEquipmentFunctionRef,
                                        _configuration=_configuration,
                                        **kwargs,
                                    )
                            
                            @classmethod
                            @functools.lru_cache()
                            def all_of(cls):
                                # we need this here to make our import statements work
                                # we must store _composed_schemas in here so the code is only run
                                # when we invoke this method. If we kept this at the class
                                # level we would get an error because the class level
                                # code would be run when this module is imported, and these composed
                                # classes don't exist yet because their module has not finished
                                # loading
                                return [
                                    ManagedFunctionAttr,
                                    cls.all_of_1,
                                ]
                    
                    
                        def __new__(
                            cls,
                            *_args: typing.Union[dict, frozendict.frozendict, str, date, datetime, uuid.UUID, int, float, decimal.Decimal, bool, None, list, tuple, bytes, io.FileIO, io.BufferedReader, ],
                            _configuration: typing.Optional[schemas.Configuration] = None,
                            **kwargs: typing.Union[schemas.AnyTypeSchema, dict, frozendict.frozendict, str, date, datetime, uuid.UUID, int, float, decimal.Decimal, None, list, tuple, bytes],
                        ) -> 'attributes':
                            return super().__new__(
                                cls,
                                *_args,
                                _configuration=_configuration,
                                **kwargs,
                            )
                    __annotations__ = {
                        "attributes": attributes,
                    }
            
            @typing.overload
            def __getitem__(self, name: typing_extensions.Literal["attributes"]) -> MetaOapg.properties.attributes: ...
            
            @typing.overload
            def __getitem__(self, name: str) -> schemas.UnsetAnyTypeSchema: ...
            
            def __getitem__(self, name: typing.Union[typing_extensions.Literal["attributes", ], str]):
                # dict_instance[name] accessor
                return super().__getitem__(name)
            
            
            @typing.overload
            def get_item_oapg(self, name: typing_extensions.Literal["attributes"]) -> typing.Union[MetaOapg.properties.attributes, schemas.Unset]: ...
            
            @typing.overload
            def get_item_oapg(self, name: str) -> typing.Union[schemas.UnsetAnyTypeSchema, schemas.Unset]: ...
            
            def get_item_oapg(self, name: typing.Union[typing_extensions.Literal["attributes", ], str]):
                return super().get_item_oapg(name)
            
        
            def __new__(
                cls,
                *_args: typing.Union[dict, frozendict.frozendict, ],
                attributes: typing.Union[MetaOapg.properties.attributes, dict, frozendict.frozendict, str, date, datetime, uuid.UUID, int, float, decimal.Decimal, bool, None, list, tuple, bytes, io.FileIO, io.BufferedReader, schemas.Unset] = schemas.unset,
                _configuration: typing.Optional[schemas.Configuration] = None,
                **kwargs: typing.Union[schemas.AnyTypeSchema, dict, frozendict.frozendict, str, date, datetime, uuid.UUID, int, float, decimal.Decimal, None, list, tuple, bytes],
            ) -> 'all_of_1':
                return super().__new__(
                    cls,
                    *_args,
                    attributes=attributes,
                    _configuration=_configuration,
                    **kwargs,
                )
        
        
        class all_of_3(
            schemas.DictSchema
        ):
        
        
            class MetaOapg:
                
                class properties:
                
                    @staticmethod
                    def CommonBeamformingFunction() -> typing.Type['CommonBeamformingFunctionSingle']:
                        return CommonBeamformingFunctionSingle
                    __annotations__ = {
                        "CommonBeamformingFunction": CommonBeamformingFunction,
                    }
            
            @typing.overload
            def __getitem__(self, name: typing_extensions.Literal["CommonBeamformingFunction"]) -> 'CommonBeamformingFunctionSingle': ...
            
            @typing.overload
            def __getitem__(self, name: str) -> schemas.UnsetAnyTypeSchema: ...
            
            def __getitem__(self, name: typing.Union[typing_extensions.Literal["CommonBeamformingFunction", ], str]):
                # dict_instance[name] accessor
                return super().__getitem__(name)
            
            
            @typing.overload
            def get_item_oapg(self, name: typing_extensions.Literal["CommonBeamformingFunction"]) -> typing.Union['CommonBeamformingFunctionSingle', schemas.Unset]: ...
            
            @typing.overload
            def get_item_oapg(self, name: str) -> typing.Union[schemas.UnsetAnyTypeSchema, schemas.Unset]: ...
            
            def get_item_oapg(self, name: typing.Union[typing_extensions.Literal["CommonBeamformingFunction", ], str]):
                return super().get_item_oapg(name)
            
        
            def __new__(
                cls,
                *_args: typing.Union[dict, frozendict.frozendict, ],
                CommonBeamformingFunction: typing.Union['CommonBeamformingFunctionSingle', schemas.Unset] = schemas.unset,
                _configuration: typing.Optional[schemas.Configuration] = None,
                **kwargs: typing.Union[schemas.AnyTypeSchema, dict, frozendict.frozendict, str, date, datetime, uuid.UUID, int, float, decimal.Decimal, None, list, tuple, bytes],
            ) -> 'all_of_3':
                return super().__new__(
                    cls,
                    *_args,
                    CommonBeamformingFunction=CommonBeamformingFunction,
                    _configuration=_configuration,
                    **kwargs,
                )
        
        @classmethod
        @functools.lru_cache()
        def all_of(cls):
            # we need this here to make our import statements work
            # we must store _composed_schemas in here so the code is only run
            # when we invoke this method. If we kept this at the class
            # level we would get an error because the class level
            # code would be run when this module is imported, and these composed
            # classes don't exist yet because their module has not finished
            # loading
            return [
                Top,
                cls.all_of_1,
                ManagedFunctionNcO,
                cls.all_of_3,
            ]


    def __new__(
        cls,
        *_args: typing.Union[dict, frozendict.frozendict, str, date, datetime, uuid.UUID, int, float, decimal.Decimal, bool, None, list, tuple, bytes, io.FileIO, io.BufferedReader, ],
        _configuration: typing.Optional[schemas.Configuration] = None,
        **kwargs: typing.Union[schemas.AnyTypeSchema, dict, frozendict.frozendict, str, date, datetime, uuid.UUID, int, float, decimal.Decimal, None, list, tuple, bytes],
    ) -> 'NrSectorCarrierSingle':
        return super().__new__(
            cls,
            *_args,
            _configuration=_configuration,
            **kwargs,
        )

from openapi_client.model.common_beamforming_function_single import CommonBeamformingFunctionSingle
from openapi_client.model.managed_function_attr import ManagedFunctionAttr
from openapi_client.model.managed_function_nc_o import ManagedFunctionNcO
from openapi_client.model.top import Top
from openapi_client.model.tx_direction import TxDirection
