# coding: utf-8

"""
    Provisioning MnS

    OAS 3.0.1 definition of the Provisioning MnS Â© 2022, 3GPP Organizational Partners (ARIB, ATIS, CCSA, ETSI, TSDSI, TTA, TTC). All rights reserved.  # noqa: E501

    The version of the OpenAPI document: 17.2.0
    Generated by: https://openapi-generator.tech
"""

from datetime import date, datetime  # noqa: F401
import decimal  # noqa: F401
import functools  # noqa: F401
import io  # noqa: F401
import re  # noqa: F401
import typing  # noqa: F401
import typing_extensions  # noqa: F401
import uuid  # noqa: F401

import frozendict  # noqa: F401

from openapi_client import schemas  # noqa: F401


class PcfFunctionSingle(
    schemas.ComposedSchema,
):
    """NOTE: This class is auto generated by OpenAPI Generator.
    Ref: https://openapi-generator.tech

    Do not edit the class manually.
    """


    class MetaOapg:
        
        
        class all_of_1(
            schemas.DictSchema
        ):
        
        
            class MetaOapg:
                
                class properties:
                    
                    
                    class attributes(
                        schemas.ComposedSchema,
                    ):
                    
                    
                        class MetaOapg:
                            
                            
                            class all_of_1(
                                schemas.DictSchema
                            ):
                            
                            
                                class MetaOapg:
                                    
                                    class properties:
                                    
                                        @staticmethod
                                        def plmnIdList() -> typing.Type['PlmnIdList']:
                                            return PlmnIdList
                                        sBIFqdn = schemas.StrSchema
                                    
                                        @staticmethod
                                        def snssaiList() -> typing.Type['SnssaiList']:
                                            return SnssaiList
                                    
                                        @staticmethod
                                        def managedNFProfile() -> typing.Type['ManagedNFProfile']:
                                            return ManagedNFProfile
                                    
                                        @staticmethod
                                        def commModelList() -> typing.Type['CommModelList']:
                                            return CommModelList
                                        configurable5QISetRef = schemas.StrSchema
                                        dynamic5QISetRef = schemas.StrSchema
                                    
                                        @staticmethod
                                        def supportedBMOList() -> typing.Type['SupportedBMOList']:
                                            return SupportedBMOList
                                        __annotations__ = {
                                            "plmnIdList": plmnIdList,
                                            "sBIFqdn": sBIFqdn,
                                            "snssaiList": snssaiList,
                                            "managedNFProfile": managedNFProfile,
                                            "commModelList": commModelList,
                                            "configurable5QISetRef": configurable5QISetRef,
                                            "dynamic5QISetRef": dynamic5QISetRef,
                                            "supportedBMOList": supportedBMOList,
                                        }
                                
                                @typing.overload
                                def __getitem__(self, name: typing_extensions.Literal["plmnIdList"]) -> 'PlmnIdList': ...
                                
                                @typing.overload
                                def __getitem__(self, name: typing_extensions.Literal["sBIFqdn"]) -> MetaOapg.properties.sBIFqdn: ...
                                
                                @typing.overload
                                def __getitem__(self, name: typing_extensions.Literal["snssaiList"]) -> 'SnssaiList': ...
                                
                                @typing.overload
                                def __getitem__(self, name: typing_extensions.Literal["managedNFProfile"]) -> 'ManagedNFProfile': ...
                                
                                @typing.overload
                                def __getitem__(self, name: typing_extensions.Literal["commModelList"]) -> 'CommModelList': ...
                                
                                @typing.overload
                                def __getitem__(self, name: typing_extensions.Literal["configurable5QISetRef"]) -> MetaOapg.properties.configurable5QISetRef: ...
                                
                                @typing.overload
                                def __getitem__(self, name: typing_extensions.Literal["dynamic5QISetRef"]) -> MetaOapg.properties.dynamic5QISetRef: ...
                                
                                @typing.overload
                                def __getitem__(self, name: typing_extensions.Literal["supportedBMOList"]) -> 'SupportedBMOList': ...
                                
                                @typing.overload
                                def __getitem__(self, name: str) -> schemas.UnsetAnyTypeSchema: ...
                                
                                def __getitem__(self, name: typing.Union[typing_extensions.Literal["plmnIdList", "sBIFqdn", "snssaiList", "managedNFProfile", "commModelList", "configurable5QISetRef", "dynamic5QISetRef", "supportedBMOList", ], str]):
                                    # dict_instance[name] accessor
                                    return super().__getitem__(name)
                                
                                
                                @typing.overload
                                def get_item_oapg(self, name: typing_extensions.Literal["plmnIdList"]) -> typing.Union['PlmnIdList', schemas.Unset]: ...
                                
                                @typing.overload
                                def get_item_oapg(self, name: typing_extensions.Literal["sBIFqdn"]) -> typing.Union[MetaOapg.properties.sBIFqdn, schemas.Unset]: ...
                                
                                @typing.overload
                                def get_item_oapg(self, name: typing_extensions.Literal["snssaiList"]) -> typing.Union['SnssaiList', schemas.Unset]: ...
                                
                                @typing.overload
                                def get_item_oapg(self, name: typing_extensions.Literal["managedNFProfile"]) -> typing.Union['ManagedNFProfile', schemas.Unset]: ...
                                
                                @typing.overload
                                def get_item_oapg(self, name: typing_extensions.Literal["commModelList"]) -> typing.Union['CommModelList', schemas.Unset]: ...
                                
                                @typing.overload
                                def get_item_oapg(self, name: typing_extensions.Literal["configurable5QISetRef"]) -> typing.Union[MetaOapg.properties.configurable5QISetRef, schemas.Unset]: ...
                                
                                @typing.overload
                                def get_item_oapg(self, name: typing_extensions.Literal["dynamic5QISetRef"]) -> typing.Union[MetaOapg.properties.dynamic5QISetRef, schemas.Unset]: ...
                                
                                @typing.overload
                                def get_item_oapg(self, name: typing_extensions.Literal["supportedBMOList"]) -> typing.Union['SupportedBMOList', schemas.Unset]: ...
                                
                                @typing.overload
                                def get_item_oapg(self, name: str) -> typing.Union[schemas.UnsetAnyTypeSchema, schemas.Unset]: ...
                                
                                def get_item_oapg(self, name: typing.Union[typing_extensions.Literal["plmnIdList", "sBIFqdn", "snssaiList", "managedNFProfile", "commModelList", "configurable5QISetRef", "dynamic5QISetRef", "supportedBMOList", ], str]):
                                    return super().get_item_oapg(name)
                                
                            
                                def __new__(
                                    cls,
                                    *_args: typing.Union[dict, frozendict.frozendict, ],
                                    plmnIdList: typing.Union['PlmnIdList', schemas.Unset] = schemas.unset,
                                    sBIFqdn: typing.Union[MetaOapg.properties.sBIFqdn, str, schemas.Unset] = schemas.unset,
                                    snssaiList: typing.Union['SnssaiList', schemas.Unset] = schemas.unset,
                                    managedNFProfile: typing.Union['ManagedNFProfile', schemas.Unset] = schemas.unset,
                                    commModelList: typing.Union['CommModelList', schemas.Unset] = schemas.unset,
                                    configurable5QISetRef: typing.Union[MetaOapg.properties.configurable5QISetRef, str, schemas.Unset] = schemas.unset,
                                    dynamic5QISetRef: typing.Union[MetaOapg.properties.dynamic5QISetRef, str, schemas.Unset] = schemas.unset,
                                    supportedBMOList: typing.Union['SupportedBMOList', schemas.Unset] = schemas.unset,
                                    _configuration: typing.Optional[schemas.Configuration] = None,
                                    **kwargs: typing.Union[schemas.AnyTypeSchema, dict, frozendict.frozendict, str, date, datetime, uuid.UUID, int, float, decimal.Decimal, None, list, tuple, bytes],
                                ) -> 'all_of_1':
                                    return super().__new__(
                                        cls,
                                        *_args,
                                        plmnIdList=plmnIdList,
                                        sBIFqdn=sBIFqdn,
                                        snssaiList=snssaiList,
                                        managedNFProfile=managedNFProfile,
                                        commModelList=commModelList,
                                        configurable5QISetRef=configurable5QISetRef,
                                        dynamic5QISetRef=dynamic5QISetRef,
                                        supportedBMOList=supportedBMOList,
                                        _configuration=_configuration,
                                        **kwargs,
                                    )
                            
                            @classmethod
                            @functools.lru_cache()
                            def all_of(cls):
                                # we need this here to make our import statements work
                                # we must store _composed_schemas in here so the code is only run
                                # when we invoke this method. If we kept this at the class
                                # level we would get an error because the class level
                                # code would be run when this module is imported, and these composed
                                # classes don't exist yet because their module has not finished
                                # loading
                                return [
                                    ManagedFunctionAttr,
                                    cls.all_of_1,
                                ]
                    
                    
                        def __new__(
                            cls,
                            *_args: typing.Union[dict, frozendict.frozendict, str, date, datetime, uuid.UUID, int, float, decimal.Decimal, bool, None, list, tuple, bytes, io.FileIO, io.BufferedReader, ],
                            _configuration: typing.Optional[schemas.Configuration] = None,
                            **kwargs: typing.Union[schemas.AnyTypeSchema, dict, frozendict.frozendict, str, date, datetime, uuid.UUID, int, float, decimal.Decimal, None, list, tuple, bytes],
                        ) -> 'attributes':
                            return super().__new__(
                                cls,
                                *_args,
                                _configuration=_configuration,
                                **kwargs,
                            )
                    __annotations__ = {
                        "attributes": attributes,
                    }
            
            @typing.overload
            def __getitem__(self, name: typing_extensions.Literal["attributes"]) -> MetaOapg.properties.attributes: ...
            
            @typing.overload
            def __getitem__(self, name: str) -> schemas.UnsetAnyTypeSchema: ...
            
            def __getitem__(self, name: typing.Union[typing_extensions.Literal["attributes", ], str]):
                # dict_instance[name] accessor
                return super().__getitem__(name)
            
            
            @typing.overload
            def get_item_oapg(self, name: typing_extensions.Literal["attributes"]) -> typing.Union[MetaOapg.properties.attributes, schemas.Unset]: ...
            
            @typing.overload
            def get_item_oapg(self, name: str) -> typing.Union[schemas.UnsetAnyTypeSchema, schemas.Unset]: ...
            
            def get_item_oapg(self, name: typing.Union[typing_extensions.Literal["attributes", ], str]):
                return super().get_item_oapg(name)
            
        
            def __new__(
                cls,
                *_args: typing.Union[dict, frozendict.frozendict, ],
                attributes: typing.Union[MetaOapg.properties.attributes, dict, frozendict.frozendict, str, date, datetime, uuid.UUID, int, float, decimal.Decimal, bool, None, list, tuple, bytes, io.FileIO, io.BufferedReader, schemas.Unset] = schemas.unset,
                _configuration: typing.Optional[schemas.Configuration] = None,
                **kwargs: typing.Union[schemas.AnyTypeSchema, dict, frozendict.frozendict, str, date, datetime, uuid.UUID, int, float, decimal.Decimal, None, list, tuple, bytes],
            ) -> 'all_of_1':
                return super().__new__(
                    cls,
                    *_args,
                    attributes=attributes,
                    _configuration=_configuration,
                    **kwargs,
                )
        
        
        class all_of_3(
            schemas.DictSchema
        ):
        
        
            class MetaOapg:
                
                class properties:
                
                    @staticmethod
                    def EP_N5() -> typing.Type['EPN5Multiple']:
                        return EPN5Multiple
                
                    @staticmethod
                    def EP_N7() -> typing.Type['EPN7Multiple']:
                        return EPN7Multiple
                
                    @staticmethod
                    def EP_N15() -> typing.Type['EPN15Multiple']:
                        return EPN15Multiple
                
                    @staticmethod
                    def EP_N16() -> typing.Type['EPN16Multiple']:
                        return EPN16Multiple
                
                    @staticmethod
                    def EP_Rx() -> typing.Type['EPRxMultiple']:
                        return EPRxMultiple
                
                    @staticmethod
                    def PredefinedPccRuleSet() -> typing.Type['PredefinedPccRuleSetSingle']:
                        return PredefinedPccRuleSetSingle
                    __annotations__ = {
                        "EP_N5": EP_N5,
                        "EP_N7": EP_N7,
                        "EP_N15": EP_N15,
                        "EP_N16": EP_N16,
                        "EP_Rx": EP_Rx,
                        "PredefinedPccRuleSet": PredefinedPccRuleSet,
                    }
            
            @typing.overload
            def __getitem__(self, name: typing_extensions.Literal["EP_N5"]) -> 'EPN5Multiple': ...
            
            @typing.overload
            def __getitem__(self, name: typing_extensions.Literal["EP_N7"]) -> 'EPN7Multiple': ...
            
            @typing.overload
            def __getitem__(self, name: typing_extensions.Literal["EP_N15"]) -> 'EPN15Multiple': ...
            
            @typing.overload
            def __getitem__(self, name: typing_extensions.Literal["EP_N16"]) -> 'EPN16Multiple': ...
            
            @typing.overload
            def __getitem__(self, name: typing_extensions.Literal["EP_Rx"]) -> 'EPRxMultiple': ...
            
            @typing.overload
            def __getitem__(self, name: typing_extensions.Literal["PredefinedPccRuleSet"]) -> 'PredefinedPccRuleSetSingle': ...
            
            @typing.overload
            def __getitem__(self, name: str) -> schemas.UnsetAnyTypeSchema: ...
            
            def __getitem__(self, name: typing.Union[typing_extensions.Literal["EP_N5", "EP_N7", "EP_N15", "EP_N16", "EP_Rx", "PredefinedPccRuleSet", ], str]):
                # dict_instance[name] accessor
                return super().__getitem__(name)
            
            
            @typing.overload
            def get_item_oapg(self, name: typing_extensions.Literal["EP_N5"]) -> typing.Union['EPN5Multiple', schemas.Unset]: ...
            
            @typing.overload
            def get_item_oapg(self, name: typing_extensions.Literal["EP_N7"]) -> typing.Union['EPN7Multiple', schemas.Unset]: ...
            
            @typing.overload
            def get_item_oapg(self, name: typing_extensions.Literal["EP_N15"]) -> typing.Union['EPN15Multiple', schemas.Unset]: ...
            
            @typing.overload
            def get_item_oapg(self, name: typing_extensions.Literal["EP_N16"]) -> typing.Union['EPN16Multiple', schemas.Unset]: ...
            
            @typing.overload
            def get_item_oapg(self, name: typing_extensions.Literal["EP_Rx"]) -> typing.Union['EPRxMultiple', schemas.Unset]: ...
            
            @typing.overload
            def get_item_oapg(self, name: typing_extensions.Literal["PredefinedPccRuleSet"]) -> typing.Union['PredefinedPccRuleSetSingle', schemas.Unset]: ...
            
            @typing.overload
            def get_item_oapg(self, name: str) -> typing.Union[schemas.UnsetAnyTypeSchema, schemas.Unset]: ...
            
            def get_item_oapg(self, name: typing.Union[typing_extensions.Literal["EP_N5", "EP_N7", "EP_N15", "EP_N16", "EP_Rx", "PredefinedPccRuleSet", ], str]):
                return super().get_item_oapg(name)
            
        
            def __new__(
                cls,
                *_args: typing.Union[dict, frozendict.frozendict, ],
                EP_N5: typing.Union['EPN5Multiple', schemas.Unset] = schemas.unset,
                EP_N7: typing.Union['EPN7Multiple', schemas.Unset] = schemas.unset,
                EP_N15: typing.Union['EPN15Multiple', schemas.Unset] = schemas.unset,
                EP_N16: typing.Union['EPN16Multiple', schemas.Unset] = schemas.unset,
                EP_Rx: typing.Union['EPRxMultiple', schemas.Unset] = schemas.unset,
                PredefinedPccRuleSet: typing.Union['PredefinedPccRuleSetSingle', schemas.Unset] = schemas.unset,
                _configuration: typing.Optional[schemas.Configuration] = None,
                **kwargs: typing.Union[schemas.AnyTypeSchema, dict, frozendict.frozendict, str, date, datetime, uuid.UUID, int, float, decimal.Decimal, None, list, tuple, bytes],
            ) -> 'all_of_3':
                return super().__new__(
                    cls,
                    *_args,
                    EP_N5=EP_N5,
                    EP_N7=EP_N7,
                    EP_N15=EP_N15,
                    EP_N16=EP_N16,
                    EP_Rx=EP_Rx,
                    PredefinedPccRuleSet=PredefinedPccRuleSet,
                    _configuration=_configuration,
                    **kwargs,
                )
        
        @classmethod
        @functools.lru_cache()
        def all_of(cls):
            # we need this here to make our import statements work
            # we must store _composed_schemas in here so the code is only run
            # when we invoke this method. If we kept this at the class
            # level we would get an error because the class level
            # code would be run when this module is imported, and these composed
            # classes don't exist yet because their module has not finished
            # loading
            return [
                Top,
                cls.all_of_1,
                ManagedFunctionNcO,
                cls.all_of_3,
            ]


    def __new__(
        cls,
        *_args: typing.Union[dict, frozendict.frozendict, str, date, datetime, uuid.UUID, int, float, decimal.Decimal, bool, None, list, tuple, bytes, io.FileIO, io.BufferedReader, ],
        _configuration: typing.Optional[schemas.Configuration] = None,
        **kwargs: typing.Union[schemas.AnyTypeSchema, dict, frozendict.frozendict, str, date, datetime, uuid.UUID, int, float, decimal.Decimal, None, list, tuple, bytes],
    ) -> 'PcfFunctionSingle':
        return super().__new__(
            cls,
            *_args,
            _configuration=_configuration,
            **kwargs,
        )

from openapi_client.model.comm_model_list import CommModelList
from openapi_client.model.epn15_multiple import EPN15Multiple
from openapi_client.model.epn16_multiple import EPN16Multiple
from openapi_client.model.epn5_multiple import EPN5Multiple
from openapi_client.model.epn7_multiple import EPN7Multiple
from openapi_client.model.eprx_multiple import EPRxMultiple
from openapi_client.model.managed_function_attr import ManagedFunctionAttr
from openapi_client.model.managed_function_nc_o import ManagedFunctionNcO
from openapi_client.model.managed_nf_profile import ManagedNFProfile
from openapi_client.model.plmn_id_list import PlmnIdList
from openapi_client.model.predefined_pcc_rule_set_single import PredefinedPccRuleSetSingle
from openapi_client.model.snssai_list import SnssaiList
from openapi_client.model.supported_bmo_list import SupportedBMOList
from openapi_client.model.top import Top
