# coding: utf-8

"""
    Provisioning MnS

    OAS 3.0.1 definition of the Provisioning MnS Â© 2022, 3GPP Organizational Partners (ARIB, ATIS, CCSA, ETSI, TSDSI, TTA, TTC). All rights reserved.  # noqa: E501

    The version of the OpenAPI document: 17.2.0
    Generated by: https://openapi-generator.tech
"""

from datetime import date, datetime  # noqa: F401
import decimal  # noqa: F401
import functools  # noqa: F401
import io  # noqa: F401
import re  # noqa: F401
import typing  # noqa: F401
import typing_extensions  # noqa: F401
import uuid  # noqa: F401

import frozendict  # noqa: F401

from openapi_client import schemas  # noqa: F401


class UpfFunctionSingle(
    schemas.ComposedSchema,
):
    """NOTE: This class is auto generated by OpenAPI Generator.
    Ref: https://openapi-generator.tech

    Do not edit the class manually.
    """


    class MetaOapg:
        
        
        class all_of_1(
            schemas.DictSchema
        ):
        
        
            class MetaOapg:
                
                class properties:
                    
                    
                    class attributes(
                        schemas.ComposedSchema,
                    ):
                    
                    
                        class MetaOapg:
                            
                            
                            class all_of_1(
                                schemas.DictSchema
                            ):
                            
                            
                                class MetaOapg:
                                    
                                    class properties:
                                    
                                        @staticmethod
                                        def plmnIdList() -> typing.Type['PlmnIdList']:
                                            return PlmnIdList
                                    
                                        @staticmethod
                                        def nRTACList() -> typing.Type['TACList']:
                                            return TACList
                                    
                                        @staticmethod
                                        def snssaiList() -> typing.Type['SnssaiList']:
                                            return SnssaiList
                                    
                                        @staticmethod
                                        def managedNFProfile() -> typing.Type['ManagedNFProfile']:
                                            return ManagedNFProfile
                                    
                                        @staticmethod
                                        def supportedBMOList() -> typing.Type['SupportedBMOList']:
                                            return SupportedBMOList
                                        __annotations__ = {
                                            "plmnIdList": plmnIdList,
                                            "nRTACList": nRTACList,
                                            "snssaiList": snssaiList,
                                            "managedNFProfile": managedNFProfile,
                                            "supportedBMOList": supportedBMOList,
                                        }
                                
                                @typing.overload
                                def __getitem__(self, name: typing_extensions.Literal["plmnIdList"]) -> 'PlmnIdList': ...
                                
                                @typing.overload
                                def __getitem__(self, name: typing_extensions.Literal["nRTACList"]) -> 'TACList': ...
                                
                                @typing.overload
                                def __getitem__(self, name: typing_extensions.Literal["snssaiList"]) -> 'SnssaiList': ...
                                
                                @typing.overload
                                def __getitem__(self, name: typing_extensions.Literal["managedNFProfile"]) -> 'ManagedNFProfile': ...
                                
                                @typing.overload
                                def __getitem__(self, name: typing_extensions.Literal["supportedBMOList"]) -> 'SupportedBMOList': ...
                                
                                @typing.overload
                                def __getitem__(self, name: str) -> schemas.UnsetAnyTypeSchema: ...
                                
                                def __getitem__(self, name: typing.Union[typing_extensions.Literal["plmnIdList", "nRTACList", "snssaiList", "managedNFProfile", "supportedBMOList", ], str]):
                                    # dict_instance[name] accessor
                                    return super().__getitem__(name)
                                
                                
                                @typing.overload
                                def get_item_oapg(self, name: typing_extensions.Literal["plmnIdList"]) -> typing.Union['PlmnIdList', schemas.Unset]: ...
                                
                                @typing.overload
                                def get_item_oapg(self, name: typing_extensions.Literal["nRTACList"]) -> typing.Union['TACList', schemas.Unset]: ...
                                
                                @typing.overload
                                def get_item_oapg(self, name: typing_extensions.Literal["snssaiList"]) -> typing.Union['SnssaiList', schemas.Unset]: ...
                                
                                @typing.overload
                                def get_item_oapg(self, name: typing_extensions.Literal["managedNFProfile"]) -> typing.Union['ManagedNFProfile', schemas.Unset]: ...
                                
                                @typing.overload
                                def get_item_oapg(self, name: typing_extensions.Literal["supportedBMOList"]) -> typing.Union['SupportedBMOList', schemas.Unset]: ...
                                
                                @typing.overload
                                def get_item_oapg(self, name: str) -> typing.Union[schemas.UnsetAnyTypeSchema, schemas.Unset]: ...
                                
                                def get_item_oapg(self, name: typing.Union[typing_extensions.Literal["plmnIdList", "nRTACList", "snssaiList", "managedNFProfile", "supportedBMOList", ], str]):
                                    return super().get_item_oapg(name)
                                
                            
                                def __new__(
                                    cls,
                                    *_args: typing.Union[dict, frozendict.frozendict, ],
                                    plmnIdList: typing.Union['PlmnIdList', schemas.Unset] = schemas.unset,
                                    nRTACList: typing.Union['TACList', schemas.Unset] = schemas.unset,
                                    snssaiList: typing.Union['SnssaiList', schemas.Unset] = schemas.unset,
                                    managedNFProfile: typing.Union['ManagedNFProfile', schemas.Unset] = schemas.unset,
                                    supportedBMOList: typing.Union['SupportedBMOList', schemas.Unset] = schemas.unset,
                                    _configuration: typing.Optional[schemas.Configuration] = None,
                                    **kwargs: typing.Union[schemas.AnyTypeSchema, dict, frozendict.frozendict, str, date, datetime, uuid.UUID, int, float, decimal.Decimal, None, list, tuple, bytes],
                                ) -> 'all_of_1':
                                    return super().__new__(
                                        cls,
                                        *_args,
                                        plmnIdList=plmnIdList,
                                        nRTACList=nRTACList,
                                        snssaiList=snssaiList,
                                        managedNFProfile=managedNFProfile,
                                        supportedBMOList=supportedBMOList,
                                        _configuration=_configuration,
                                        **kwargs,
                                    )
                            
                            @classmethod
                            @functools.lru_cache()
                            def all_of(cls):
                                # we need this here to make our import statements work
                                # we must store _composed_schemas in here so the code is only run
                                # when we invoke this method. If we kept this at the class
                                # level we would get an error because the class level
                                # code would be run when this module is imported, and these composed
                                # classes don't exist yet because their module has not finished
                                # loading
                                return [
                                    ManagedFunctionAttr,
                                    cls.all_of_1,
                                ]
                    
                    
                        def __new__(
                            cls,
                            *_args: typing.Union[dict, frozendict.frozendict, str, date, datetime, uuid.UUID, int, float, decimal.Decimal, bool, None, list, tuple, bytes, io.FileIO, io.BufferedReader, ],
                            _configuration: typing.Optional[schemas.Configuration] = None,
                            **kwargs: typing.Union[schemas.AnyTypeSchema, dict, frozendict.frozendict, str, date, datetime, uuid.UUID, int, float, decimal.Decimal, None, list, tuple, bytes],
                        ) -> 'attributes':
                            return super().__new__(
                                cls,
                                *_args,
                                _configuration=_configuration,
                                **kwargs,
                            )
                    __annotations__ = {
                        "attributes": attributes,
                    }
            
            @typing.overload
            def __getitem__(self, name: typing_extensions.Literal["attributes"]) -> MetaOapg.properties.attributes: ...
            
            @typing.overload
            def __getitem__(self, name: str) -> schemas.UnsetAnyTypeSchema: ...
            
            def __getitem__(self, name: typing.Union[typing_extensions.Literal["attributes", ], str]):
                # dict_instance[name] accessor
                return super().__getitem__(name)
            
            
            @typing.overload
            def get_item_oapg(self, name: typing_extensions.Literal["attributes"]) -> typing.Union[MetaOapg.properties.attributes, schemas.Unset]: ...
            
            @typing.overload
            def get_item_oapg(self, name: str) -> typing.Union[schemas.UnsetAnyTypeSchema, schemas.Unset]: ...
            
            def get_item_oapg(self, name: typing.Union[typing_extensions.Literal["attributes", ], str]):
                return super().get_item_oapg(name)
            
        
            def __new__(
                cls,
                *_args: typing.Union[dict, frozendict.frozendict, ],
                attributes: typing.Union[MetaOapg.properties.attributes, dict, frozendict.frozendict, str, date, datetime, uuid.UUID, int, float, decimal.Decimal, bool, None, list, tuple, bytes, io.FileIO, io.BufferedReader, schemas.Unset] = schemas.unset,
                _configuration: typing.Optional[schemas.Configuration] = None,
                **kwargs: typing.Union[schemas.AnyTypeSchema, dict, frozendict.frozendict, str, date, datetime, uuid.UUID, int, float, decimal.Decimal, None, list, tuple, bytes],
            ) -> 'all_of_1':
                return super().__new__(
                    cls,
                    *_args,
                    attributes=attributes,
                    _configuration=_configuration,
                    **kwargs,
                )
        
        
        class all_of_3(
            schemas.DictSchema
        ):
        
        
            class MetaOapg:
                
                class properties:
                
                    @staticmethod
                    def EP_N3() -> typing.Type['EPN3Multiple']:
                        return EPN3Multiple
                
                    @staticmethod
                    def EP_N4() -> typing.Type['EPN4Multiple']:
                        return EPN4Multiple
                
                    @staticmethod
                    def EP_N6() -> typing.Type['EPN6Multiple']:
                        return EPN6Multiple
                
                    @staticmethod
                    def EP_N9() -> typing.Type['EPN9Multiple']:
                        return EPN9Multiple
                
                    @staticmethod
                    def EP_S5U() -> typing.Type['EPS5UMultiple']:
                        return EPS5UMultiple
                    __annotations__ = {
                        "EP_N3": EP_N3,
                        "EP_N4": EP_N4,
                        "EP_N6": EP_N6,
                        "EP_N9": EP_N9,
                        "EP_S5U": EP_S5U,
                    }
            
            @typing.overload
            def __getitem__(self, name: typing_extensions.Literal["EP_N3"]) -> 'EPN3Multiple': ...
            
            @typing.overload
            def __getitem__(self, name: typing_extensions.Literal["EP_N4"]) -> 'EPN4Multiple': ...
            
            @typing.overload
            def __getitem__(self, name: typing_extensions.Literal["EP_N6"]) -> 'EPN6Multiple': ...
            
            @typing.overload
            def __getitem__(self, name: typing_extensions.Literal["EP_N9"]) -> 'EPN9Multiple': ...
            
            @typing.overload
            def __getitem__(self, name: typing_extensions.Literal["EP_S5U"]) -> 'EPS5UMultiple': ...
            
            @typing.overload
            def __getitem__(self, name: str) -> schemas.UnsetAnyTypeSchema: ...
            
            def __getitem__(self, name: typing.Union[typing_extensions.Literal["EP_N3", "EP_N4", "EP_N6", "EP_N9", "EP_S5U", ], str]):
                # dict_instance[name] accessor
                return super().__getitem__(name)
            
            
            @typing.overload
            def get_item_oapg(self, name: typing_extensions.Literal["EP_N3"]) -> typing.Union['EPN3Multiple', schemas.Unset]: ...
            
            @typing.overload
            def get_item_oapg(self, name: typing_extensions.Literal["EP_N4"]) -> typing.Union['EPN4Multiple', schemas.Unset]: ...
            
            @typing.overload
            def get_item_oapg(self, name: typing_extensions.Literal["EP_N6"]) -> typing.Union['EPN6Multiple', schemas.Unset]: ...
            
            @typing.overload
            def get_item_oapg(self, name: typing_extensions.Literal["EP_N9"]) -> typing.Union['EPN9Multiple', schemas.Unset]: ...
            
            @typing.overload
            def get_item_oapg(self, name: typing_extensions.Literal["EP_S5U"]) -> typing.Union['EPS5UMultiple', schemas.Unset]: ...
            
            @typing.overload
            def get_item_oapg(self, name: str) -> typing.Union[schemas.UnsetAnyTypeSchema, schemas.Unset]: ...
            
            def get_item_oapg(self, name: typing.Union[typing_extensions.Literal["EP_N3", "EP_N4", "EP_N6", "EP_N9", "EP_S5U", ], str]):
                return super().get_item_oapg(name)
            
        
            def __new__(
                cls,
                *_args: typing.Union[dict, frozendict.frozendict, ],
                EP_N3: typing.Union['EPN3Multiple', schemas.Unset] = schemas.unset,
                EP_N4: typing.Union['EPN4Multiple', schemas.Unset] = schemas.unset,
                EP_N6: typing.Union['EPN6Multiple', schemas.Unset] = schemas.unset,
                EP_N9: typing.Union['EPN9Multiple', schemas.Unset] = schemas.unset,
                EP_S5U: typing.Union['EPS5UMultiple', schemas.Unset] = schemas.unset,
                _configuration: typing.Optional[schemas.Configuration] = None,
                **kwargs: typing.Union[schemas.AnyTypeSchema, dict, frozendict.frozendict, str, date, datetime, uuid.UUID, int, float, decimal.Decimal, None, list, tuple, bytes],
            ) -> 'all_of_3':
                return super().__new__(
                    cls,
                    *_args,
                    EP_N3=EP_N3,
                    EP_N4=EP_N4,
                    EP_N6=EP_N6,
                    EP_N9=EP_N9,
                    EP_S5U=EP_S5U,
                    _configuration=_configuration,
                    **kwargs,
                )
        
        @classmethod
        @functools.lru_cache()
        def all_of(cls):
            # we need this here to make our import statements work
            # we must store _composed_schemas in here so the code is only run
            # when we invoke this method. If we kept this at the class
            # level we would get an error because the class level
            # code would be run when this module is imported, and these composed
            # classes don't exist yet because their module has not finished
            # loading
            return [
                Top,
                cls.all_of_1,
                ManagedFunctionNcO,
                cls.all_of_3,
            ]


    def __new__(
        cls,
        *_args: typing.Union[dict, frozendict.frozendict, str, date, datetime, uuid.UUID, int, float, decimal.Decimal, bool, None, list, tuple, bytes, io.FileIO, io.BufferedReader, ],
        _configuration: typing.Optional[schemas.Configuration] = None,
        **kwargs: typing.Union[schemas.AnyTypeSchema, dict, frozendict.frozendict, str, date, datetime, uuid.UUID, int, float, decimal.Decimal, None, list, tuple, bytes],
    ) -> 'UpfFunctionSingle':
        return super().__new__(
            cls,
            *_args,
            _configuration=_configuration,
            **kwargs,
        )

from openapi_client.model.epn3_multiple import EPN3Multiple
from openapi_client.model.epn4_multiple import EPN4Multiple
from openapi_client.model.epn6_multiple import EPN6Multiple
from openapi_client.model.epn9_multiple import EPN9Multiple
from openapi_client.model.eps5_u_multiple import EPS5UMultiple
from openapi_client.model.managed_function_attr import ManagedFunctionAttr
from openapi_client.model.managed_function_nc_o import ManagedFunctionNcO
from openapi_client.model.managed_nf_profile import ManagedNFProfile
from openapi_client.model.plmn_id_list import PlmnIdList
from openapi_client.model.snssai_list import SnssaiList
from openapi_client.model.supported_bmo_list import SupportedBMOList
from openapi_client.model.tac_list import TACList
from openapi_client.model.top import Top
