# coding: utf-8

"""
    Provisioning MnS

    OAS 3.0.1 definition of the Provisioning MnS Â© 2022, 3GPP Organizational Partners (ARIB, ATIS, CCSA, ETSI, TSDSI, TTA, TTC). All rights reserved.  # noqa: E501

    The version of the OpenAPI document: 17.2.0
    Generated by: https://openapi-generator.tech
"""

from openapi_client.paths.class_nameid.delete import ClassNameidDelete
from openapi_client.paths.class_nameid.get import ClassNameidGet
from openapi_client.paths.class_nameid.patch import ClassNameidPatch
from openapi_client.paths.class_nameid.put import ClassNameidPut


class DefaultApi(
    ClassNameidDelete,
    ClassNameidGet,
    ClassNameidPatch,
    ClassNameidPut,
):
    """NOTE: This class is auto generated by OpenAPI Generator
    Ref: https://openapi-generator.tech

    Do not edit the class manually.
    """
    pass
